<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Statistics and Plots | STA238: Probability, Statistics, and Data Analysis</title>
  <meta name="description" content="This book represents part of the course materials for STA238 at the University of Toronto" />
  <meta name="generator" content="bookdown 0.13 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Statistics and Plots | STA238: Probability, Statistics, and Data Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This book represents part of the course materials for STA238 at the University of Toronto" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Statistics and Plots | STA238: Probability, Statistics, and Data Analysis" />
  
  <meta name="twitter:description" content="This book represents part of the course materials for STA238 at the University of Toronto" />
  

<meta name="author" content="Alison Gibbs and Alex Stringer" />


<meta name="date" content="2019-10-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="supplement-to-chapters-15-and-16.html"/>
<link rel="next" href="error.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STA238 University of Toronto</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="supplement-to-chapters-15-and-16.html"><a href="supplement-to-chapters-15-and-16.html"><i class="fa fa-check"></i><b>2</b> Supplement to Chapters 15 and 16</a><ul>
<li class="chapter" data-level="2.1" data-path="supplement-to-chapters-15-and-16.html"><a href="supplement-to-chapters-15-and-16.html#old-faithful"><i class="fa fa-check"></i><b>2.1</b> Old Faithful</a><ul>
<li class="chapter" data-level="2.1.1" data-path="supplement-to-chapters-15-and-16.html"><a href="supplement-to-chapters-15-and-16.html#read-in-the-data"><i class="fa fa-check"></i><b>2.1.1</b> Read in the data</a></li>
<li class="chapter" data-level="2.1.2" data-path="supplement-to-chapters-15-and-16.html"><a href="supplement-to-chapters-15-and-16.html#graphical-summaries"><i class="fa fa-check"></i><b>2.1.2</b> Graphical Summaries</a></li>
<li class="chapter" data-level="2.1.3" data-path="supplement-to-chapters-15-and-16.html"><a href="supplement-to-chapters-15-and-16.html#numerical-summaries-ch-16"><i class="fa fa-check"></i><b>2.1.3</b> Numerical Summaries (Ch 16)</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="supplement-to-chapters-15-and-16.html"><a href="supplement-to-chapters-15-and-16.html#drilling"><i class="fa fa-check"></i><b>2.2</b> Drilling</a><ul>
<li class="chapter" data-level="2.2.1" data-path="supplement-to-chapters-15-and-16.html"><a href="supplement-to-chapters-15-and-16.html#read-in-data"><i class="fa fa-check"></i><b>2.2.1</b> Read in data</a></li>
<li class="chapter" data-level="2.2.2" data-path="supplement-to-chapters-15-and-16.html"><a href="supplement-to-chapters-15-and-16.html#graphical-summaries-1"><i class="fa fa-check"></i><b>2.2.2</b> Graphical summaries</a></li>
<li class="chapter" data-level="2.2.3" data-path="supplement-to-chapters-15-and-16.html"><a href="supplement-to-chapters-15-and-16.html#numerical-summaries"><i class="fa fa-check"></i><b>2.2.3</b> Numerical summaries</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="supplement-to-chapters-15-and-16.html"><a href="supplement-to-chapters-15-and-16.html#exercises"><i class="fa fa-check"></i><b>2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html"><i class="fa fa-check"></i><b>3</b> Statistics and Plots</a><ul>
<li class="chapter" data-level="3.1" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#descriptive-analysis"><i class="fa fa-check"></i><b>3.2</b> Descriptive analysis</a><ul>
<li class="chapter" data-level="3.2.1" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#exercises-1"><i class="fa fa-check"></i><b>3.2.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#exploratory-analysis"><i class="fa fa-check"></i><b>3.3</b> Exploratory analysis</a><ul>
<li class="chapter" data-level="3.3.1" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#exercises-2"><i class="fa fa-check"></i><b>3.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#prescriptive-analysis"><i class="fa fa-check"></i><b>3.4</b> Prescriptive analysis</a><ul>
<li class="chapter" data-level="3.4.1" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#exercises-3"><i class="fa fa-check"></i><b>3.4.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#rental-housing-in-toronto"><i class="fa fa-check"></i><b>3.5</b> Rental housing in Toronto</a><ul>
<li class="chapter" data-level="3.5.1" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#load-the-data"><i class="fa fa-check"></i><b>3.5.1</b> Load the data</a></li>
<li class="chapter" data-level="3.5.2" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#analysis-i-what-does-the-data-look-like"><i class="fa fa-check"></i><b>3.5.2</b> Analysis I: what does the data look like?</a></li>
<li class="chapter" data-level="3.5.3" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#analysis-ii-do-different-wards-have-different-quality-housing"><i class="fa fa-check"></i><b>3.5.3</b> Analysis II: Do different wards have different quality housing?</a></li>
<li class="chapter" data-level="3.5.4" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#analysis-iii-trends-in-quality-over-time"><i class="fa fa-check"></i><b>3.5.4</b> Analysis III: trends in quality over time</a></li>
<li class="chapter" data-level="3.5.5" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#summary"><i class="fa fa-check"></i><b>3.5.5</b> Summary</a></li>
<li class="chapter" data-level="3.5.6" data-path="statistics-and-plots.html"><a href="statistics-and-plots.html#exercises-4"><i class="fa fa-check"></i><b>3.5.6</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="error.html"><a href="error.html"><i class="fa fa-check"></i><b>4</b> Error</a><ul>
<li class="chapter" data-level="4.1" data-path="error.html"><a href="error.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="error.html"><a href="error.html#statistical-error-under-repeated-sampling"><i class="fa fa-check"></i><b>4.2</b> Statistical error under repeated sampling</a><ul>
<li class="chapter" data-level="4.2.1" data-path="error.html"><a href="error.html#the-idea"><i class="fa fa-check"></i><b>4.2.1</b> The idea</a></li>
<li class="chapter" data-level="4.2.2" data-path="error.html"><a href="error.html#example-coin-flipping"><i class="fa fa-check"></i><b>4.2.2</b> Example: coin flipping</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="mathematical-models.html"><a href="mathematical-models.html"><i class="fa fa-check"></i><b>5</b> Mathematical Models</a></li>
<li class="chapter" data-level="6" data-path="computational-models.html"><a href="computational-models.html"><i class="fa fa-check"></i><b>6</b> Computational Models</a></li>
<li class="chapter" data-level="7" data-path="incorporating-what-i-know-using-prior-information-to-inform-inferences.html"><a href="incorporating-what-i-know-using-prior-information-to-inform-inferences.html"><i class="fa fa-check"></i><b>7</b> Incorporating what I know: using prior information to inform inferences</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STA238: Probability, Statistics, and Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistics-and-plots" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Statistics and Plots</h1>
<div id="introduction-1" class="section level2">
<h2><span class="header-section-number">3.1</span> Introduction</h2>
<p>How do we turn <strong>data</strong> into <strong>information</strong>?</p>
<p>This question is highly <em>contextual</em>. The meaning of <em>information</em> will change depending on the task. And <em>data</em> isn’t a well-defined concept on its own. Even <a href="Webster&#39;s%20dictionary">https://www.merriam-webster.com/dictionary/data</a> defines data <em>implicitly</em>, as “a basis for…”.</p>
<p>In this chapter we will discuss the use of data in the pursuit of three types of information: <strong>descriptive</strong>, <strong>exploratory</strong>, and <strong>prescriptive</strong>.</p>
</div>
<div id="descriptive-analysis" class="section level2">
<h2><span class="header-section-number">3.2</span> Descriptive analysis</h2>
<p>The most simple type of information available from a set of data is to <em>describe</em> what you have in front of you. The decisions you make about <em>what</em> to describe and <em>how</em> to describe it make a big difference.</p>
<p>There is no one correct way to analyze any given dataset. You will make judgements,
and assumptions, and you will have to justify and explain them. These judgements
and assumptions can have a profound impact on the <em>story</em> you tell using your data.</p>
<p>For example, consider a famous dataset containing information on smoking and mortality.
The data is available in the <code>R</code> package <code>faraway</code>. We may load the package and data
and retrieve information on it as follows:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1"><span class="co"># install.packages(&quot;faraway&quot;) # Run this to install the faraway package, which has useful datasets</span></a>
<a class="sourceLine" id="cb68-2" title="2"><span class="kw">library</span>(faraway) <span class="co"># Attach the faraway package</span></a>
<a class="sourceLine" id="cb68-3" title="3"><span class="kw">data</span>(<span class="st">&quot;femsmoke&quot;</span>) <span class="co"># Load the &quot;femsmoke&quot; data</span></a>
<a class="sourceLine" id="cb68-4" title="4"><span class="co"># ?femsmoke # Run this to open the help page for the dataset.</span></a></code></pre></div>
<p>Lines in <code>R</code> that begin with a pound sign (or “hashtag” for the younger, more hip reader), <span class="math inline">\(\#\)</span>,
are comments and are not run. Remove the <span class="math inline">\(\#\)</span> to run the code.</p>
<p>We see from the help page, and associated reference to the paper in the <em>American Statistician</em>,
that the data comes from asking women in Whickham, England, whether they smoke or not,
and then following up in 20 years to see if they died.</p>
<p>In <em>describing</em> the context surrouning the data—a quite natural step to take—we have achieved our first example of a descriptive analysis. We didn’t even use and numbers or code. Just describing what the data <em>is</em> counts. And it’s important, because as we learned in the introduction, information can’t exist without <em>context</em>.</p>
<p>To go further in our descriptive analysis, we need some more <em>quantitative</em> pieces of descriptive information. What might we want to know about our data? Some ideas:</p>
<ul>
<li>How many <strong>observations</strong> are there in the data, and what does an observation represent in the context of how the data was collected?</li>
<li>How many <strong>variables</strong> are present in the data, and what does each variable represent in the context of how the data was collected?</li>
<li>How might we summarize each variable? We might compute a <strong>mean</strong> and a <strong>five-number summary</strong> for “continuous” variables, and a <strong>table of counts</strong> for “categorical” variables (more on this later…).</li>
</ul>
<p>Let’s see how we can obtain these descriptive measures in <code>R</code>:</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" title="1"><span class="co"># install.packages(&quot;tidyverse&quot;)</span></a>
<a class="sourceLine" id="cb69-2" title="2"><span class="co"># install.packages(&quot;SMPracticals&quot;) # For datasets</span></a>
<a class="sourceLine" id="cb69-3" title="3"><span class="kw">library</span>(tidyverse) <span class="co"># We use a LOT of functions from this package.</span></a>
<a class="sourceLine" id="cb69-4" title="4"><span class="co"># Get the number of observations (rows), variables, and an idea</span></a>
<a class="sourceLine" id="cb69-5" title="5"><span class="co"># of what the data looks like:</span></a>
<a class="sourceLine" id="cb69-6" title="6"><span class="kw">glimpse</span>(femsmoke)</a></code></pre></div>
<pre><code>## Observations: 28
## Variables: 4
## $ y      &lt;dbl&gt; 2, 1, 3, 5, 14, 7, 27, 12, 51, 40, 29, 101, 13, 64, 53, 6…
## $ smoker &lt;fct&gt; yes, no, yes, no, yes, no, yes, no, yes, no, yes, no, yes…
## $ dead   &lt;fct&gt; yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, ye…
## $ age    &lt;fct&gt; 18-24, 18-24, 25-34, 25-34, 35-44, 35-44, 45-54, 45-54, 5…</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" title="1"><span class="co"># One observation represents a count of people in each category.</span></a>
<a class="sourceLine" id="cb71-2" title="2"><span class="co"># How many people?</span></a>
<a class="sourceLine" id="cb71-3" title="3">femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb71-4" title="4"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_people =</span> <span class="kw">sum</span>(y)) <span class="co"># The summarize() function lets you compute summaries of variables in your dataframe</span></a></code></pre></div>
<pre><code>##   num_people
## 1       1314</code></pre>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" title="1"><span class="co"># How many smokers?</span></a>
<a class="sourceLine" id="cb73-2" title="2">femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb73-3" title="3"><span class="st">  </span><span class="kw">filter</span>(smoker <span class="op">==</span><span class="st"> &quot;yes&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># filter() lets you choose which rows to keep</span></a>
<a class="sourceLine" id="cb73-4" title="4"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_smokers =</span> <span class="kw">sum</span>(y))</a></code></pre></div>
<pre><code>##   num_smokers
## 1         582</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1"><span class="co"># How many non-smokers?</span></a>
<a class="sourceLine" id="cb75-2" title="2">femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb75-3" title="3"><span class="st">  </span><span class="kw">filter</span>(smoker <span class="op">==</span><span class="st"> &quot;no&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb75-4" title="4"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_non_smokers =</span> <span class="kw">sum</span>(y))</a></code></pre></div>
<pre><code>##   num_non_smokers
## 1             732</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" title="1"><span class="co"># We can get both those numbers at the same time:</span></a>
<a class="sourceLine" id="cb77-2" title="2">femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb77-3" title="3"><span class="st">  </span><span class="kw">group_by</span>(smoker) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># group_by() makes summarize() compute summaries within levels of a variable</span></a>
<a class="sourceLine" id="cb77-4" title="4"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_people =</span> <span class="kw">sum</span>(y))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   smoker num_people
##   &lt;fct&gt;       &lt;dbl&gt;
## 1 yes           582
## 2 no            732</code></pre>
<p>There are lots of other descriptive statistics you could calculate.</p>
<p><em>Summary</em>: descriptive analysis involves communicating properties of a dataset, and the context behind the dataset.</p>
<div id="exercises-1" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>How many non-smoking 18-24 year olds are there in the <code>femsmoke</code> data? Answer using <code>filter()</code>.</p></li>
<li><p>How many smokers died? Answer using <code>filter()</code>.</p></li>
<li><p>How many 45-55 year olds did not die?</p></li>
<li><p>Compute the following table using <code>group_by()</code> and <code>summarize()</code>:</p></li>
</ol>
<pre><code>## # A tibble: 7 x 2
##   age   num_people
##   &lt;fct&gt;      &lt;dbl&gt;
## 1 18-24        117
## 2 25-34        281
## 3 35-44        230
## 4 45-54        208
## 5 55-64        236
## 6 65-74        165
## 7 75+           77</code></pre>
</div>
</div>
<div id="exploratory-analysis" class="section level2">
<h2><span class="header-section-number">3.3</span> Exploratory analysis</h2>
<p>Descriptive analyses are an important task any time you are working with data. However, they don’t accomplish anything <em>new</em>; they just, well, <em>describe</em> what you have.</p>
<p>An <strong>exploratory analysis</strong> involves looking for patterns or structure in the available data. We can use what we find to make decisions or come to conclusions.</p>
<p>One thing we can <em>choose</em> to explore about these data is whether we
observe any apparent <em>association</em> between smoking and mortality. To investigate any such associations, we can look at <em>the observed mortality rates</em>
for smokers and non-smokers. This is <em>exploratory</em>—not <em>descriptive</em>—because we are going beyond simply saying what the data looks like. We are looking for a pattern, namely, “do smokers die more or less frequently than non-smokers?”</p>
<p>Exploratory analyses involve decisions made by us, the investigator. They are naturally <em>subjective</em>. Different decisions can lead to uncovering different patterns. For example:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" title="1"><span class="co"># Compute the mortality rate for smokers and non-smokers.</span></a>
<a class="sourceLine" id="cb80-2" title="2"><span class="co"># To do this, create a dataframe containing the numbers of smokers</span></a>
<a class="sourceLine" id="cb80-3" title="3"><span class="co"># and non-smokers</span></a>
<a class="sourceLine" id="cb80-4" title="4">smoker_numbers &lt;-<span class="st"> </span>femsmoke <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># The %&gt;% operator lets you form sequences of operations</span></a>
<a class="sourceLine" id="cb80-5" title="5"><span class="st">  </span><span class="kw">group_by</span>(smoker) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># group_by() makes all the following operations happen within groups</span></a>
<a class="sourceLine" id="cb80-6" title="6"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_people =</span> <span class="kw">sum</span>(y)) <span class="co"># Count the number of people who are smokers and not smokers </span></a>
<a class="sourceLine" id="cb80-7" title="7">smoker_numbers</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   smoker num_people
##   &lt;fct&gt;       &lt;dbl&gt;
## 1 yes           582
## 2 no            732</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" title="1"><span class="co"># Now, compute the number of people who died out of the smokers and non-smokers</span></a>
<a class="sourceLine" id="cb82-2" title="2"><span class="co"># This looks the same as above, except we now filter() only the people who died.</span></a>
<a class="sourceLine" id="cb82-3" title="3">smoker_numbers_dead &lt;-<span class="st"> </span>femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb82-4" title="4"><span class="st">  </span><span class="kw">filter</span>(dead <span class="op">==</span><span class="st"> &quot;yes&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Retains rows where dead == &quot;yes&quot; only</span></a>
<a class="sourceLine" id="cb82-5" title="5"><span class="st">  </span><span class="kw">group_by</span>(smoker) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb82-6" title="6"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_dead =</span> <span class="kw">sum</span>(y))</a>
<a class="sourceLine" id="cb82-7" title="7">smoker_numbers_dead</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   smoker num_dead
##   &lt;fct&gt;     &lt;dbl&gt;
## 1 yes         139
## 2 no          230</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" title="1"><span class="co"># Now, we join these two tables together and compute the mortality rates by group.</span></a>
<a class="sourceLine" id="cb84-2" title="2">smoker_numbers <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb84-3" title="3"><span class="st">  </span><span class="kw">inner_join</span>(smoker_numbers_dead,<span class="dt">by =</span> <span class="st">&quot;smoker&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Joins rows with the same value of &quot;smoker&quot;</span></a>
<a class="sourceLine" id="cb84-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mort_rate =</span> num_dead<span class="op">/</span>num_people) <span class="co"># mutate() creates a new variable, which can be a function of the other variables in the dataframe.</span></a></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   smoker num_people num_dead mort_rate
##   &lt;fct&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 yes           582      139     0.239
## 2 no            732      230     0.314</code></pre>
<p>See anything interesting?</p>
<p>What went wrong? Why are we observing that smokers have a <em>lower</em> mortality rate than
non-smokers? This contradicts the <em>context</em> surrounding this analysis, which in this case is the large body of formal and anecdotal evidence suggesting that smoking is harmful to health.</p>
<p>Did we make a mistake?</p>
<p>One thing we definitely did was ignore some present information. Specifically,
we also know how old the women were. How can we include this information in our
exploratory analysis? We can compute mortality rates by age:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" title="1">smoker_numbers_age &lt;-<span class="st"> </span>femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb86-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(smoker,age) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Now we&#39;re grouping by smoker AND age. The rest of the code remains unchanged.</span></a>
<a class="sourceLine" id="cb86-3" title="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_people =</span> <span class="kw">sum</span>(y))</a>
<a class="sourceLine" id="cb86-4" title="4"></a>
<a class="sourceLine" id="cb86-5" title="5">smoker_numbers_age_dead &lt;-<span class="st"> </span>femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb86-6" title="6"><span class="st">  </span><span class="kw">filter</span>(dead <span class="op">==</span><span class="st"> &quot;yes&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb86-7" title="7"><span class="st">  </span><span class="kw">group_by</span>(smoker,age) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb86-8" title="8"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_dead =</span> <span class="kw">sum</span>(y))</a>
<a class="sourceLine" id="cb86-9" title="9"></a>
<a class="sourceLine" id="cb86-10" title="10">smoker_numbers_age <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb86-11" title="11"><span class="st">  </span><span class="kw">inner_join</span>(smoker_numbers_age_dead,<span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;smoker&quot;</span>,<span class="st">&quot;age&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb86-12" title="12"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mort_rate =</span> num_dead<span class="op">/</span>num_people)</a></code></pre></div>
<pre><code>## # A tibble: 14 x 5
## # Groups:   smoker [2]
##    smoker age   num_people num_dead mort_rate
##    &lt;fct&gt;  &lt;fct&gt;      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
##  1 yes    18-24         55        2    0.0364
##  2 yes    25-34        124        3    0.0242
##  3 yes    35-44        109       14    0.128 
##  4 yes    45-54        130       27    0.208 
##  5 yes    55-64        115       51    0.443 
##  6 yes    65-74         36       29    0.806 
##  7 yes    75+           13       13    1     
##  8 no     18-24         62        1    0.0161
##  9 no     25-34        157        5    0.0318
## 10 no     35-44        121        7    0.0579
## 11 no     45-54         78       12    0.154 
## 12 no     55-64        121       40    0.331 
## 13 no     65-74        129      101    0.783 
## 14 no     75+           64       64    1</code></pre>
<p>Older people are more likely to die within the 20 year followup period.
However, examining the raw counts of people in each group, we also see that
<em>in these data, older people are less likely to smoke</em> than younger people. So
<em>in these data</em>, less smokers died, because less smokers were old, and more
old people died.</p>
<p>But was our first analysis wrong? No. Our first analysis was fine: we computed
the mortality rate in each group. The problem was in the reporting, or the way
we told the story. We didn’t provide enough information when we said “the mortality
rate for smokers was lower than for non-smokers”. We should have mentioned that
this is <em>averaging over all age groups</em>. Even when we include age in the analysis,
we ought to mention the fact that there are a whole lot of variables we <em>could</em>
have measured but didn’t, and we are implicitly averaging over these too.</p>
<p>Before moving on, get some practice doing exploratory analysis with the following
exercises:</p>
<div id="exercises-2" class="section level3">
<h3><span class="header-section-number">3.3.1</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li>What is the <em>relative risk</em> of mortality—the ratio of the mortality rates—for
smoking 18-24 year olds vs non-smoking 18-24 year olds? Compute the answer manually by
reading the numbers off the above table. Then compute it using <code>R</code> by doing the
following:</li>
</ol>
<ul>
<li>Create two datasets using <code>filter()</code>: one containing smokers and one containing
non-smokers. <code>filter()</code> out only the 18-24 year olds. This gives you two datasets
each with only one row. For example, <code>smokers &lt;- femsmoke %&gt;% filter(smoker == &quot;yes&quot;,age = &quot;18-24&quot;)</code>.</li>
<li><code>inner_join()</code> the two datasets together, using <code>age</code> as the <code>by</code> variable:
<code>smokers %&gt;% inner_join(???,by = &quot;age&quot;)</code></li>
</ul>
<ol style="list-style-type: decimal">
<li><em>Advanced</em>: modify the above steps to create the following table of relative mortality rates. You should start from a cleaned up version of the mortality rate by age table:</li>
</ol>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" title="1">rates_by_age &lt;-<span class="st"> </span>smoker_numbers_age <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb88-2" title="2"><span class="kw">inner_join</span>(smoker_numbers_age_dead,<span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;smoker&quot;</span>,<span class="st">&quot;age&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb88-3" title="3"><span class="kw">mutate</span>(<span class="dt">mort_rate =</span> num_dead<span class="op">/</span>num_people) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb88-4" title="4"><span class="kw">ungroup</span>() <span class="co"># The data was previously grouped, we don&#39;t want this anymore</span></a></code></pre></div>
<p>Use <code>dplyr::select()</code> to remove and rename columns, see <code>?dplyr::select</code>.</p>
<pre><code>## # A tibble: 7 x 4
##   age   smoker_mort_rate nonsmoker_mort_rate relative_risk
##   &lt;fct&gt;            &lt;dbl&gt;               &lt;dbl&gt;         &lt;dbl&gt;
## 1 18-24           0.0364              0.0161         2.25 
## 2 25-34           0.0242              0.0318         0.760
## 3 35-44           0.128               0.0579         2.22 
## 4 45-54           0.208               0.154          1.35 
## 5 55-64           0.443               0.331          1.34 
## 6 65-74           0.806               0.783          1.03 
## 7 75+             1                   1              1</code></pre>
</div>
</div>
<div id="prescriptive-analysis" class="section level2">
<h2><span class="header-section-number">3.4</span> Prescriptive analysis</h2>
<p>Descriptive anlaysis is about understanding the data that we have. Exploratory anlaysis is about finding patterns in the data you have.</p>
<p><strong>Prescriptive analysis</strong> is about using the data you have to explicitly support making a decision or coming to a conclusion. Often the data has been collected for a reason. Scientific experiments, surveys, questionnaries given when applying for a mortage or insurance product; these aren’t just “fishing expeditions”. These data are collected in the hopes of coming to a specific conclusion. We might wish to state the efficacy of a clinical treatment, or decide which politician is going to win an election, or whether to grant somebody a loan or underwrite an insurance policy.</p>
<p>Often a prescriptive analysis is conducted <em>using exactly the same steps</em> as an exploratory analysis. Here, you must be very careful. Knowing what you want the data to say can, and very often does, influence choices made by the researcher about how to analyze the data. This is often referred to as “researcher degrees of freedom”.</p>
<p>For example, perhaps the smoking data was collected with the explicit purpose of supporting anti-smoking initiatives. This renders the above analysis <em>prescriptive</em>, because we know what we want to see: we want smokers to have a higher mortality rate than non-smokers in these data. In this <em>context</em>, let’s re-compute the above table of mortality rates:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" title="1">smoker_numbers <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb90-2" title="2"><span class="st">  </span><span class="kw">inner_join</span>(smoker_numbers_dead,<span class="dt">by =</span> <span class="st">&quot;smoker&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb90-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mort_rate =</span> num_dead<span class="op">/</span>num_people)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   smoker num_people num_dead mort_rate
##   &lt;fct&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 yes           582      139     0.239
## 2 no            732      230     0.314</code></pre>
<p>…hm. It appears that the data is telling us the opposite of what we thought it would.</p>
<p>What do we do now? Well, we ignored some information, namely the subjects’ ages. So let’s use those:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" title="1">smoker_numbers_age <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb92-2" title="2"><span class="st">  </span><span class="kw">inner_join</span>(smoker_numbers_age_dead,<span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;smoker&quot;</span>,<span class="st">&quot;age&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb92-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mort_rate =</span> num_dead<span class="op">/</span>num_people)</a></code></pre></div>
<pre><code>## # A tibble: 14 x 5
## # Groups:   smoker [2]
##    smoker age   num_people num_dead mort_rate
##    &lt;fct&gt;  &lt;fct&gt;      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
##  1 yes    18-24         55        2    0.0364
##  2 yes    25-34        124        3    0.0242
##  3 yes    35-44        109       14    0.128 
##  4 yes    45-54        130       27    0.208 
##  5 yes    55-64        115       51    0.443 
##  6 yes    65-74         36       29    0.806 
##  7 yes    75+           13       13    1     
##  8 no     18-24         62        1    0.0161
##  9 no     25-34        157        5    0.0318
## 10 no     35-44        121        7    0.0579
## 11 no     45-54         78       12    0.154 
## 12 no     55-64        121       40    0.331 
## 13 no     65-74        129      101    0.783 
## 14 no     75+           64       64    1</code></pre>
<p>Oh! It’s because older people are more likely to die, and less likely to smoke.</p>
<p>We performed the exact same steps in our prescriptive analysis as we did in our exploratory analysis. Can we make the same conclusions?</p>
<p>This is where we need to be careful. When we go into the data with a specific question in mind, <strong>we have to report everything we see that relates to this question</strong>. We ought to report that</p>
<ul>
<li>Smokers had a lower mortality rate than non-smokers, and</li>
<li>there were more young smokers than old smokers in the data, and</li>
<li>younger people had a lower mortality rate than older people, in our data.</li>
</ul>
<p>Context matters! If we just reported that “controlling for age, smokers have a higher mortality rate than non-smokers”, we would be communicating a potentially <em>spurious</em> conclusion. What’s so important about age? We could have controlled for other variables and perhaps seen different relationships. These “researcher degrees of freedom” are a big force behind what is known as the “reproducibility crisis” in modern science.</p>
<div id="exercises-3" class="section level3">
<h3><span class="header-section-number">3.4.1</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li>For each of the following analyses, state whether you think it is <em>descriptive</em>, <em>exploratory</em> or <em>prescriptive</em>, and say why.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>I work for an urban planning think tank and I want to present to our clients a proposal that advocates the development of green spaces in urban centres as a public health initiative. I use Health Canada data on obesity and Open Data Toronto data on locations of greenspaces to investigate whether areas with more green spaces have less obesity.</li>
<li>I am interested in which streets have more heavily enforced parking laws, so I download data on all parking tickets given in Toronto last year and make a map.</li>
</ol>
</div>
</div>
<div id="rental-housing-in-toronto" class="section level2">
<h2><span class="header-section-number">3.5</span> Rental housing in Toronto</h2>
<p>The RentSafeTO: Apartment Building Standards program is designed to help renters
in the city of Toronto make informed choices about where to live, and to enforce
a minimum standard of quality upon rental units within the city. With rents
skyrocketing and home ownership not a reasonable option for most, having an
informed view of the rental market is imperative for Toronto residents. It also helps keep leaders
accountable, specifically if we focus on social and community housing buildings.</p>
<p>Comprehensive and fairly clean data from the program, along with specific
information, is available at <a href="https://open.toronto.ca/dataset/apartment-building-evaluation/" class="uri">https://open.toronto.ca/dataset/apartment-building-evaluation/</a>.
Data for the following were downloaded on <code>2019/09/16</code>.</p>
<p>To start your analysis, go now and download the data
and open it in a spreadsheet and have a look. Familiarize yourselves with the
variable descriptions and how the data were collected; the <em>documentation</em>. This somewhat tedious
task is a first step of <strong>any</strong> data analysis, in academia, industry, government,
or wherever.</p>
<div id="load-the-data" class="section level3">
<h3><span class="header-section-number">3.5.1</span> Load the data</h3>
<p>The data are stored in a <code>.csv</code> file, which stands for “comma-separated-values”.
Storing data in a text file with a separator, usually a comma, is very common.
These are referred to as “flat files” in an industrial context, to distinguish
them from data stored in databases.</p>
<p>We may read the data into <code>R</code> using the <code>read_csv</code> function in the <code>readr</code> package.
The <code>readr</code> package is part of the <code>tidyverse</code> package that we used before, so if
you installed that package, you have it loaded.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" title="1"><span class="co"># https://open.toronto.ca/dataset/apartment-building-evaluation/</span></a>
<a class="sourceLine" id="cb94-2" title="2"><span class="co"># install.packages(&quot;readr&quot;)</span></a>
<a class="sourceLine" id="cb94-3" title="3"></a>
<a class="sourceLine" id="cb94-4" title="4"><span class="co"># Read the data in. This means call the readr::read_csv() function, point it</span></a>
<a class="sourceLine" id="cb94-5" title="5"><span class="co"># to where you saved the data on your computer, and then save the result to a</span></a>
<a class="sourceLine" id="cb94-6" title="6"><span class="co"># variable. I am naming this variable &#39;apartmentdata&#39;.</span></a>
<a class="sourceLine" id="cb94-7" title="7"><span class="co"># Type ?readr::read_csv if you want to read about this function.</span></a>
<a class="sourceLine" id="cb94-8" title="8">apartmentdata &lt;-<span class="st"> </span>readr<span class="op">::</span><span class="kw">read_csv</span>(</a>
<a class="sourceLine" id="cb94-9" title="9">  <span class="dt">file =</span> <span class="st">&quot;./data/apartment-data/toronto-apartment-building-evaluations.csv&quot;</span></a>
<a class="sourceLine" id="cb94-10" title="10">)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   EVALUATION_COMPLETED_ON = col_character(),
##   PROPERTY_TYPE = col_character(),
##   RESULTS_OF_SCORE = col_character(),
##   SITE_ADDRESS = col_character(),
##   WARD = col_character()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<p>The message displayed is telling you that <code>readr::read_csv()</code> guessed at what
kind of data were in each column, i.e. numbers, letters, dates, etc. You should
make sure, as I have while writing, that these are what you expect. You can
get a concise view of this dataset using the <code>glimpse</code> function in the <code>dplyr</code>
package, which is automatically loaded when you load the <code>tidyverse</code>:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb97-1" title="1"><span class="kw">glimpse</span>(apartmentdata)</a></code></pre></div>
<pre><code>## Observations: 3,446
## Variables: 32
## $ `_id`                       &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1…
## $ BALCONY_GUARDS              &lt;dbl&gt; NA, NA, NA, NA, 5, NA, 5, 3, 4, 4, 3…
## $ CONFIRMED_STOREYS           &lt;dbl&gt; 28, 4, 3, 3, 29, 3, 7, 18, 17, 32, 4…
## $ CONFIRMED_UNITS             &lt;dbl&gt; 457, 15, 26, 10, 272, 12, 95, 287, 3…
## $ ELEVATORS                   &lt;dbl&gt; 4, NA, NA, NA, 5, NA, 5, 4, 5, 4, NA…
## $ ENTRANCE_DOORS_WINDOWS      &lt;dbl&gt; 3, 3, 3, 4, 5, 4, 4, 4, 3, 4, 4, 3, …
## $ ENTRANCE_LOBBY              &lt;dbl&gt; 4, 3, 3, 4, 5, 4, 4, 4, 4, 4, 4, 4, …
## $ EVALUATION_COMPLETED_ON     &lt;chr&gt; &quot;04/03/2019&quot;, &quot;05/24/2018&quot;, &quot;07/11/2…
## $ EXTERIOR_CLADDING           &lt;dbl&gt; 3, 4, 4, 4, 5, 4, 5, 4, 4, 3, 3, 4, …
## $ EXTERIOR_GROUNDS            &lt;dbl&gt; 3, 4, 3, 3, 5, 4, 5, 4, 3, 4, 3, 4, …
## $ EXTERIOR_WALKWAYS           &lt;dbl&gt; 3, 5, 4, 4, 5, 4, 5, 4, 3, 4, 4, 3, …
## $ GARBAGE_BIN_STORAGE_AREA    &lt;dbl&gt; 3, 4, 3, 3, 4, 3, 3, 3, 4, 4, 4, 4, …
## $ GARBAGE_CHUTE_ROOMS         &lt;dbl&gt; 3, NA, NA, NA, 5, NA, 5, 4, 3, 4, 5,…
## $ GRAFFITI                    &lt;dbl&gt; 5, 5, 5, 5, 5, 4, 5, 4, 3, 4, 5, 5, …
## $ INTERIOR_LIGHTING_LEVELS    &lt;dbl&gt; 3, 4, 4, 4, 5, 4, 4, 3, 3, 4, 3, 4, …
## $ INTERIOR_WALL_CEILING_FLOOR &lt;dbl&gt; 4, 3, 4, 4, 5, 4, 4, 3, 4, 4, 4, 3, …
## $ INTERNAL_GUARDS_HANDRAILS   &lt;dbl&gt; 3, 4, 3, 4, 5, 4, 5, 4, 4, 4, 5, 4, …
## $ NO_OF_AREAS_EVALUATED       &lt;dbl&gt; 18, 14, 14, 13, 19, 16, 17, 18, 19, …
## $ OTHER_FACILITIES            &lt;dbl&gt; 4, NA, NA, NA, 5, NA, NA, NA, NA, NA…
## $ PARKING_AREA                &lt;dbl&gt; 2, NA, NA, NA, 4, 3, 5, 2, 4, 4, 2, …
## $ PROPERTY_TYPE               &lt;chr&gt; &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;SO…
## $ RESULTS_OF_SCORE            &lt;chr&gt; &quot;Evaluation needs to be conducted in…
## $ RSN                         &lt;dbl&gt; 4365723, 4364249, 4408585, 4288126, …
## $ SCORE                       &lt;dbl&gt; 71, 77, 71, 78, 98, 76, 93, 72, 74, …
## $ SECURITY                    &lt;dbl&gt; 4, 3, 3, 4, 5, 4, 5, 3, 4, 4, 4, 4, …
## $ SITE_ADDRESS                &lt;chr&gt; &quot;2350  DUNDAS ST W&quot;, &quot;9  STAG HILL D…
## $ STAIRWELLS                  &lt;dbl&gt; 4, 4, 3, 4, 5, 4, 5, 4, 4, 4, 3, 4, …
## $ STORAGE_AREAS_LOCKERS       &lt;dbl&gt; NA, NA, NA, NA, NA, 4, NA, NA, 3, 4,…
## $ WARD                        &lt;chr&gt; &quot;04&quot;, &quot;19&quot;, &quot;11&quot;, &quot;04&quot;, &quot;07&quot;, &quot;03&quot;, …
## $ WATER_PEN_EXT_BLDG_ELEMENTS &lt;dbl&gt; 4, 4, 4, 4, 5, 4, 5, 4, 5, 3, 3, 4, …
## $ YEAR_BUILT                  &lt;dbl&gt; 1976, 1953, 1948, 1920, 2017, 1967, …
## $ YEAR_REGISTERED             &lt;dbl&gt; 2018, 2018, 2018, 2017, 2018, 2017, …</code></pre>
<p>That’s bigger than the <code>smoking</code> data! 3,446 rental apartment buildings, each with
32 factors measured. The buliding’s address and Ward number are in there, which are
helpful for characterizing neighbourhoods.</p>
</div>
<div id="analysis-i-what-does-the-data-look-like" class="section level3">
<h3><span class="header-section-number">3.5.2</span> Analysis I: what does the data look like?</h3>
<p>As a first step, we want to get an idea of what our data “looks like”. This typically means picking some interesting variables and summarizing their distributions somehow.</p>
<p>Which variables to pick will depend on the context. Often it will be clear which variables are important, and sometimes not.</p>
<p>Because you read the documentation and familiarized yourselves with the variables in the dataset, you know that there is a variable called <code>SCORE</code> which sums up the individual category scores for each building. In the context of determining building quality, this seems like an important variable to look at.</p>
<p>We’ll summarize the distribution of <code>SCORE</code> using a five-number summary and mean, and a <strong>histogram</strong> with a <strong>kernel density estimate</strong>.</p>
<p>First, prepare the data for analysis:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb99-1" title="1"><span class="co"># First, select only the columns you want</span></a>
<a class="sourceLine" id="cb99-2" title="2"><span class="co"># This isn&#39;t strictly necessary but trust me, it makes </span></a>
<a class="sourceLine" id="cb99-3" title="3"><span class="co"># debugging WAY easier.</span></a>
<a class="sourceLine" id="cb99-4" title="4"><span class="co"># I&#39;m also renaming the columns so the dataframe looks prettier.</span></a>
<a class="sourceLine" id="cb99-5" title="5"><span class="co"># Again, trust me. This stuff matters.</span></a>
<a class="sourceLine" id="cb99-6" title="6">apartmentclean &lt;-<span class="st"> </span>apartmentdata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb99-7" title="7"><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(SCORE)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Remove apartments with missing scores</span></a>
<a class="sourceLine" id="cb99-8" title="8"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="dt">ward =</span> WARD,</a>
<a class="sourceLine" id="cb99-9" title="9">                <span class="dt">score =</span> SCORE,</a>
<a class="sourceLine" id="cb99-10" title="10">                <span class="dt">property_type =</span> PROPERTY_TYPE,</a>
<a class="sourceLine" id="cb99-11" title="11">                <span class="dt">year_built =</span> YEAR_BUILT,</a>
<a class="sourceLine" id="cb99-12" title="12">                <span class="dt">address =</span> SITE_ADDRESS</a>
<a class="sourceLine" id="cb99-13" title="13">  )</a>
<a class="sourceLine" id="cb99-14" title="14"><span class="kw">glimpse</span>(apartmentclean) <span class="co"># Much nicer!</span></a></code></pre></div>
<pre><code>## Observations: 3,437
## Variables: 5
## $ ward          &lt;chr&gt; &quot;04&quot;, &quot;19&quot;, &quot;11&quot;, &quot;04&quot;, &quot;07&quot;, &quot;03&quot;, &quot;17&quot;, &quot;17&quot;, &quot;0…
## $ score         &lt;dbl&gt; 71, 77, 71, 78, 98, 76, 93, 72, 74, 78, 73, 76, 57…
## $ property_type &lt;chr&gt; &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;SOCIAL HOUSING&quot;,…
## $ year_built    &lt;dbl&gt; 1976, 1953, 1948, 1920, 2017, 1967, 2015, 1970, 19…
## $ address       &lt;chr&gt; &quot;2350  DUNDAS ST W&quot;, &quot;9  STAG HILL DR&quot;, &quot;130  MACP…</code></pre>
<p>To compute the five-number summary (plus mean), use the <code>summary()</code> function in <code>R</code>. I also want to know the <em>standard deviation</em> of <code>SCORE</code>:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb101-1" title="1"><span class="kw">summary</span>(apartmentclean<span class="op">$</span>score)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   37.00   68.00   72.00   72.28   77.00   99.00</code></pre>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb103-1" title="1"><span class="kw">sd</span>(apartmentclean<span class="op">$</span>score,<span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## [1] 7.117172</code></pre>
<p>The worst building in the city has a total score of 37, and the best gets 99. The median score—half the buildings in the city have a lower score, and half a higher score than this—is 72, and this roughly equals the mean of 72.28. 25% of buildings score higher than 77, and 25% score lower than 68. So most buildings seem to fall within less than one standard deviation of the mean, which indicates that these data are fairly <em>concentrated</em> about their mean.</p>
<p>To provide some context, go look up your own building (if you live in a rental building) or that of a friend in the data. Where does your building fall in terms of quality within Toronto?</p>
<p>So far we have used tabular displays to summarize our data, for both the <code>smoking</code> and the apartment data. To communicate more information at once, we can use a <strong>plot</strong>.</p>
<p>The most common type of plot for visualizing an empirical estimate of a probability distribution is a <strong>histogram</strong>. A histogram bins the data into ranges and, by default, counts the number of data points in each range. We will tell the plotting function to compute the <em>proportion</em> of data in each range, and then <em>normalize</em> the results so that the plot integrates to one (and hence estimates a probability density). This won’t change the shape of the plot.</p>
<p>We can make a histogram in <code>R</code> as follows:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb105-1" title="1"><span class="co"># The ggplot2 package is loaded as part of the tidyverse</span></a>
<a class="sourceLine" id="cb105-2" title="2">score_histogram &lt;-<span class="st"> </span>apartmentclean <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb105-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> score)) <span class="op">+</span><span class="st"> </span><span class="co"># Tell ggplot to use score on the x axis</span></a>
<a class="sourceLine" id="cb105-4" title="4"><span class="st">  </span><span class="kw">theme_light</span>() <span class="op">+</span><span class="st"> </span><span class="co"># Make the plot pretty</span></a>
<a class="sourceLine" id="cb105-5" title="5"><span class="st">  </span><span class="kw">geom_histogram</span>( <span class="co"># Makes a histogram</span></a>
<a class="sourceLine" id="cb105-6" title="6">    <span class="kw">aes</span>(<span class="dt">y =</span> ..density..),</a>
<a class="sourceLine" id="cb105-7" title="7">    <span class="dt">bins =</span> <span class="dv">20</span>,</a>
<a class="sourceLine" id="cb105-8" title="8">    <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>,</a>
<a class="sourceLine" id="cb105-9" title="9">    <span class="dt">fill =</span> <span class="st">&quot;lightgrey&quot;</span></a>
<a class="sourceLine" id="cb105-10" title="10">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb105-11" title="11"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of RentSafeTO Apartment Building Standards score&quot;</span>,</a>
<a class="sourceLine" id="cb105-12" title="12">       <span class="dt">x =</span> <span class="st">&quot;Score&quot;</span>,</a>
<a class="sourceLine" id="cb105-13" title="13">       <span class="dt">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb105-14" title="14"><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">30</span>,<span class="dv">100</span>,<span class="dt">by =</span> <span class="dv">5</span>))</a>
<a class="sourceLine" id="cb105-15" title="15"></a>
<a class="sourceLine" id="cb105-16" title="16">score_histogram</a></code></pre></div>
<p><img src="book_files/figure-html/apartment-descriptive-3-1.png" width="672" /></p>
<p>It appears that most buildings are in the 65 to 85 range. (Interesting point: at time of writing I am in the process of moving from one building to another; current building has a 66, new building has an 86 :D).</p>
<p>Another common estimate of a distribution is a <strong>kernel density estimate</strong>, which can be viewed as a more “continuous” version of a histogram that actually draws a curve on the plot that is supposed to represent the (empirical) probability density of the data. We can add this to our plot very quickly:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb106-1" title="1">score_histogram <span class="op">+</span></a>
<a class="sourceLine" id="cb106-2" title="2"><span class="st">  </span><span class="kw">geom_density</span>()</a></code></pre></div>
<p><img src="book_files/figure-html/apartment-descriptive-4-1.png" width="672" /></p>
</div>
<div id="analysis-ii-do-different-wards-have-different-quality-housing" class="section level3">
<h3><span class="header-section-number">3.5.3</span> Analysis II: Do different wards have different quality housing?</h3>
<p>A Ward is an administrative district within the city that has a single city
counsellor. If I’m thinking about moving to, or within, Toronto, I want to know:
<strong>Do different wards have different quality housing?</strong>.</p>
<p>In order to address this question we need to decide on the following:</p>
<ul>
<li><strong>Variable of interest</strong>. How do we <em>quantify</em> our research question? We need
to pick a <em>measure of quality</em>. Picking different measures can lead to different
conclusions.</li>
<li><strong>Filters</strong>. Do we look at all apartment buildings? Should we look only at those
built after, or before, a certain date? Only those that meet a certain minimum,
or maximum, standard of quality according to our definition? Are there any other
kinds of decisions we might have to consider?</li>
<li><strong>Methods</strong>. What kind of statistical tools should we use to address our research
question? We need to pick descriptive statistics to report, and decide whether
we want to include other auxillary variables in the analysis.</li>
<li><strong>Conclusions</strong>. How do we report our results? Tables, charts, maps? Should we
include subjective, editorial commentary, or let the data speak for
themselves?</li>
</ul>
<p>This is already overwhelming! Let’s make an attempt at it. I propose:</p>
<ul>
<li>Our <strong>variable of interest</strong> should be <code>SCORE</code>, which you know (because you
read the documentation…) is the “overall score of the buliding”. Higher is
better. The actual formula is included in the documentation of the data.</li>
<li>We will <strong>filter</strong> the data to only include buildings where <code>PROPERTY_TYPE == 'PRIVATE'</code>,
which will restrict our analysis to not include social housing. The quality of social
housing is an important social justice issue (that you will investigate in the exercises)
but it’s somewhat separate (?) from the question of where to look for rental housing.</li>
<li>Our <strong>methods</strong> will include looking at a table of average scores for each ward.
We will also look at whether older or newer buildings receive better scores.</li>
<li>We will summarize our <strong>conclusions</strong> through a subjective assessment of the
above table of average scores.</li>
</ul>
<p>With these decisions made, we may proceed with our analysis using the <code>tidyverse</code>
as follows:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" title="1"><span class="co"># Apply filter(s).</span></a>
<a class="sourceLine" id="cb107-2" title="2">apartmentfiltered &lt;-<span class="st"> </span>apartmentclean <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb107-3" title="3"><span class="st">  </span><span class="kw">filter</span>(property_type <span class="op">==</span><span class="st"> &quot;PRIVATE&quot;</span>)</a>
<a class="sourceLine" id="cb107-4" title="4"><span class="co"># When filtering, always compare the filtered and unfiltered data to ensure</span></a>
<a class="sourceLine" id="cb107-5" title="5"><span class="co"># the result is as expected:</span></a>
<a class="sourceLine" id="cb107-6" title="6"><span class="kw">glimpse</span>(apartmentclean)</a></code></pre></div>
<pre><code>## Observations: 3,437
## Variables: 5
## $ ward          &lt;chr&gt; &quot;04&quot;, &quot;19&quot;, &quot;11&quot;, &quot;04&quot;, &quot;07&quot;, &quot;03&quot;, &quot;17&quot;, &quot;17&quot;, &quot;0…
## $ score         &lt;dbl&gt; 71, 77, 71, 78, 98, 76, 93, 72, 74, 78, 73, 76, 57…
## $ property_type &lt;chr&gt; &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;SOCIAL HOUSING&quot;,…
## $ year_built    &lt;dbl&gt; 1976, 1953, 1948, 1920, 2017, 1967, 2015, 1970, 19…
## $ address       &lt;chr&gt; &quot;2350  DUNDAS ST W&quot;, &quot;9  STAG HILL DR&quot;, &quot;130  MACP…</code></pre>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" title="1"><span class="kw">glimpse</span>(apartmentfiltered)</a></code></pre></div>
<pre><code>## Observations: 2,873
## Variables: 5
## $ ward          &lt;chr&gt; &quot;04&quot;, &quot;19&quot;, &quot;11&quot;, &quot;07&quot;, &quot;03&quot;, &quot;17&quot;, &quot;17&quot;, &quot;08&quot;, &quot;1…
## $ score         &lt;dbl&gt; 71, 77, 71, 98, 76, 93, 72, 74, 78, 73, 76, 57, 70…
## $ property_type &lt;chr&gt; &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;PRIVA…
## $ year_built    &lt;dbl&gt; 1976, 1953, 1948, 2017, 1967, 2015, 1970, 1976, 19…
## $ address       &lt;chr&gt; &quot;2350  DUNDAS ST W&quot;, &quot;9  STAG HILL DR&quot;, &quot;130  MACP…</code></pre>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb111-1" title="1"><span class="kw">nrow</span>(apartmentclean) <span class="op">-</span><span class="st"> </span><span class="kw">nrow</span>(apartmentfiltered) <span class="co"># Dropped 567 rows.</span></a></code></pre></div>
<pre><code>## [1] 564</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb113-1" title="1"><span class="co"># Now create the table of averages:</span></a>
<a class="sourceLine" id="cb113-2" title="2">apartmentfiltered <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb113-3" title="3"><span class="st">  </span><span class="kw">group_by</span>(ward) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb113-4" title="4"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">avg_score =</span> <span class="kw">mean</span>(score))</a></code></pre></div>
<pre><code>## # A tibble: 26 x 2
##    ward  avg_score
##    &lt;chr&gt;     &lt;dbl&gt;
##  1 01         71.5
##  2 02         73.0
##  3 03         70.5
##  4 04         68.2
##  5 05         71.7
##  6 06         72.1
##  7 07         69.8
##  8 08         73.5
##  9 09         67.5
## 10 10         72.2
## # … with 16 more rows</code></pre>
<p>Bah! What happened? Why are there these <code>NA</code> values?</p>
<p><code>NA</code> is the value <code>R</code> uses to mean “missing”. We have to hope that whether a
rental apartment building’s <code>score</code> is missing <em>is not related</em> to what that score <em>is</em>,
that is, we hope apartments with higher or lower scores aren’t missing more often.</p>
<p>We will ignore missingness for now. To do this, use the <code>na.rm = TRUE</code> option in
<code>mean</code>:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb115-1" title="1">apartmentsummary &lt;-<span class="st"> </span>apartmentfiltered <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb115-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(ward) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb115-3" title="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">avg_score =</span> <span class="kw">mean</span>(score,<span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</a>
<a class="sourceLine" id="cb115-4" title="4">apartmentsummary</a></code></pre></div>
<pre><code>## # A tibble: 26 x 2
##    ward  avg_score
##    &lt;chr&gt;     &lt;dbl&gt;
##  1 01         71.5
##  2 02         73.0
##  3 03         70.5
##  4 04         68.2
##  5 05         71.7
##  6 06         72.1
##  7 07         69.8
##  8 08         73.5
##  9 09         67.5
## 10 10         72.2
## # … with 16 more rows</code></pre>
<p>This isn’t a super friendly way of comparing these 26 numbers. We need some kind
od <strong>visualization</strong>, or <strong>plot</strong>, so we can take one look and get an idea of
what is going on.</p>
<p>In order to pick what kind of plot to make, we have to understand what types
of variables we are attempting to compare. Broadly speaking, variables can
either be <strong>continuous</strong> or <strong>categorical</strong>.</p>
<p>A <strong>continuous</strong> variable consists of
numbers. You can always compare the <em>order</em> of two values of a continuous variable
(say whether one is bigger than the other), because its values are just numbers.</p>
<p>A <strong>categorical</strong> variable takes values from a finite (discrete) set. These values
can be anything. Categorical variables sometimes have values which can be compared,
like “big”, “medium”, “small”; but often the values are not inherently comparable.</p>
<p>In the case of the table of average scores by ward, we will consider <code>avg_score</code>
to be a <strong>continuous</strong> variable and <code>ward</code> to be a <strong>categorical</strong> variable. Wards
are labelled with numbers, yes, but they are not inherently comparable; they are
areas within the city. It wouldn’t make sense to say that ward 2 were “less” than
ward 17. We could have labelled them “A”, “B”, “C”,… and the meaning would
have been the same.</p>
<p>One common visualization used to compare values of a <strong>continuous</strong> variable
with values of a <strong>categorical</strong> variable is a <strong>dot chart</strong>. A dot chart contains
the values of the categorical variable on the x-axis and the values of the
continuous variable on the y-axis. You can take one look and see whether there is
any pattern in values of the continuous variable with respect to the categorical
variable.</p>
<p>We create a <strong>dot chart</strong> to visualize these summary statistics using the <code>ggplot2</code>
package. This is also included with the <code>tidyverse</code> (surprise!):</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb117-1" title="1">apartmentsummary <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb117-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> ward,<span class="dt">y =</span> avg_score)) <span class="op">+</span><span class="st"> </span><span class="co"># Set up the variable mappings</span></a>
<a class="sourceLine" id="cb117-3" title="3"><span class="st">  </span><span class="kw">theme_light</span>() <span class="op">+</span><span class="st"> </span><span class="co"># Make it pretty</span></a>
<a class="sourceLine" id="cb117-4" title="4"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">pch =</span> <span class="dv">21</span>,<span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>,<span class="dt">fill =</span> <span class="st">&quot;grey&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="co"># Add the bars</span></a>
<a class="sourceLine" id="cb117-5" title="5"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Average ABS score shows moderate variability across wards in Toronto&quot;</span>,</a>
<a class="sourceLine" id="cb117-6" title="6">       <span class="dt">x =</span> <span class="st">&quot;Ward&quot;</span>,</a>
<a class="sourceLine" id="cb117-7" title="7">       <span class="dt">y =</span> <span class="st">&quot;Average ABS Score&quot;</span>) <span class="co"># Informative title</span></a></code></pre></div>
<p><img src="book_files/figure-html/barchart-apartment-1-1.png" width="672" /></p>
<p>It looks like some wards are better than others. Or are they? Can we make any
definitive conclusions based on this?</p>
</div>
<div id="analysis-iii-trends-in-quality-over-time" class="section level3">
<h3><span class="header-section-number">3.5.4</span> Analysis III: trends in quality over time</h3>
<p>Let’s go further and analyze some other interesting aspects of these data. I’m
interested in knowing: <strong>Are newer buildings higher quality</strong>?</p>
<p>We have the <code>score</code>
and the <code>year_built</code>, and we’d like to investigate whether newer buildings (higher
<code>year_built</code>) have higher <code>scores</code>. We have another decision to make. We could
consider <code>year_built</code> to be a categorical variable, and make a bar chart. Or,
we could consider it to be a continuous variable.</p>
<p>Because values of <code>year_built</code> are inherently comparable, and because <em>our research
question involves making such comparisons</em>, we will consider <code>year_built</code> to be
a continuous variable.</p>
<p>One type of plot used to compare continuous variables is a <strong>scatterplot</strong>. A
scatterplot has continuous variables on the x- and y-axes, and draws a point (or
bubble) at each place in the two-dimensional plane where a datapoint occurs. We
can make this kind of plot in <code>ggplot2</code> as well. This time, we use the raw
(well, cleaned and filtered) data:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb118-1" title="1">apartmentfiltered <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb118-2" title="2"><span class="st">  </span><span class="kw">filter</span>(year_built <span class="op">&gt;</span><span class="st"> </span><span class="dv">1900</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb118-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year_built,<span class="dt">y =</span> score)) <span class="op">+</span></a>
<a class="sourceLine" id="cb118-4" title="4"><span class="st">  </span><span class="kw">theme_light</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb118-5" title="5"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">pch =</span> <span class="dv">21</span>,<span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>,<span class="dt">fill =</span> <span class="st">&quot;grey&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="co"># pch=21 makes the bubbles hollow, looks nice</span></a>
<a class="sourceLine" id="cb118-6" title="6"><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">1900</span>,<span class="dv">2020</span>,<span class="dt">by=</span><span class="dv">10</span>)) <span class="op">+</span><span class="st"> </span><span class="co"># Set the x-axis range</span></a>
<a class="sourceLine" id="cb118-7" title="7"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Less rental buildings are being built recently, but they are of higher quality&quot;</span>,</a>
<a class="sourceLine" id="cb118-8" title="8">       <span class="dt">x =</span> <span class="st">&quot;Year Built&quot;</span>,</a>
<a class="sourceLine" id="cb118-9" title="9">       <span class="dt">y =</span> <span class="st">&quot;ABS Score&quot;</span>)</a></code></pre></div>
<p><img src="book_files/figure-html/apartment-plot-2-1.png" width="672" /></p>
<p>Very interesting. You can clearly see the baby boom of the 1950’s to 1970’s, followed by a massive slowdown in construction during the economic slump in the 1980’s, and a complete stop when rent control was introduced in 1991 (remember, these are <em>rental</em> buildings only). Then, we see a new wave of
rental building construction, and the new buildings seem to be of higher quality.</p>
<p>What are the highest and lowest quality rental buildings in Toronto?</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb119-1" title="1"><span class="co"># Get the 10 highest scoring buildings</span></a>
<a class="sourceLine" id="cb119-2" title="2">apartmentfiltered <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb119-3" title="3"><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(score)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Sort the data, descending, by score</span></a>
<a class="sourceLine" id="cb119-4" title="4"><span class="st">  </span><span class="kw">slice</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>) <span class="co"># Take the first ten- i.e. the top ten</span></a></code></pre></div>
<pre><code>## # A tibble: 10 x 5
##    ward  score property_type year_built address                 
##    &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;                   
##  1 YY       99 PRIVATE             2018 561  SHERBOURNE ST      
##  2 17       99 PRIVATE             2017 123  PARKWAY FOREST DR  
##  3 16       99 PRIVATE             1963 70  PARKWOODS VILLAGE DR
##  4 07       98 PRIVATE             2017 2  VENA WAY             
##  5 17       97 PRIVATE             1968 24  FOREST MANOR RD     
##  6 12       96 PRIVATE             1960 42  GLEN ELM AVE        
##  7 13       95 PRIVATE             2017 252  VICTORIA ST        
##  8 02       95 PRIVATE             1969 500  SCARLETT RD        
##  9 16       95 PRIVATE             1962 67  PARKWOODS VILLAGE DR
## 10 07       95 PRIVATE             2016 6  VENA WAY</code></pre>
<p>Wow. I know where I want to live.</p>
</div>
<div id="summary" class="section level3">
<h3><span class="header-section-number">3.5.5</span> Summary</h3>
<p>We have seen how even something simple like trying to figure out whether
different areas of the city have different quality housing can require
a lot of decision making. And these decisions require expertise. By taking
a principled approach to learning <strong>data analysis</strong>, you are <em>empowering</em>
yourself to live a life that is better informed.</p>
<p>But notice that we didn’t really answer any questions in this chapter. We
saw some rough patterns, but were they real? If we made different decisions, or if we <em>sampled different data</em>, would we have seen different patterns?</p>
<p>In order to understand what the problem is and how to approach it, we
need to take a more detailed look at the concept of <strong>error</strong>. This is the
subject of Chapter 2.</p>
</div>
<div id="exercises-4" class="section level3">
<h3><span class="header-section-number">3.5.6</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Take each of the analyses we have performed on the Toronto rental data and say whether you think it’s <strong>descriptive</strong>, <strong>exploratory</strong>, or <strong>prescriptive</strong>, or a mix, and say why.</p></li>
<li><p>What is that “YY” ward that shows up in the dot plot? Investigate this unusual observation.</p></li>
<li><p>Read the documentation online and choose three variables that you find the most interesting. Reproduce the analyses I, II and III using your variables. Is there more or less variability across wards than with <code>score</code>?</p></li>
<li><p>What is the ward with the highest average score? In what ward is/are the building(s) with the highest score(s)? Is this the same ward, or not? Would you expect the ward with the highest average to also have the highest-scoring buildings? Repeat this question with the lowest scoring buildings instead of the highest.</p></li>
<li><p>If you live in a rental apartment, find it in these data. If not, find a friend’s place. How does your building compare to other buildings in your ward? Does it score higher or lower? The <code>filter()</code> function is your friend here, or you can use <code>apartmentfiltered %&gt;% arrange(SITE_ADDRESS) %&gt;% print(n = Inf)</code> and then find yours in the list manually.</p></li>
<li><p>Combine the analyses of sections 2.3.2 and 2.3.3. with that of 2.3.4. Specifically, make a table and a boxplot of the average score by year. This means replace <code>ward</code> by <code>year_built</code> in the analysis of sections 2.3.2. and 2.3.3. Do your conclusions change when comparing with 2.3.4? Why or why not? Would you expect this to always be the case?</p></li>
<li><p><em>Advanced</em>: analyze the quality of <strong>social housing</strong> in Toronto. Perform a similar analysis to what we performed here for <code>PROPERTY_TYPE == 'PRIVATE'</code>, but instead for <code>PROPERTY_TYPE %in% c('SOCIAL HOUSING','TCHC')</code> (equivalent to <code>PROPERTY_TYPE != 'PRIVATE'</code>). Does the quality of social housing in Toronto vary greatly across different wards? Is it improving or degrading over time? Do you think we have enough information here to definitively answer these questions?</p></li>
</ol>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="supplement-to-chapters-15-and-16.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="error.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["book.pdf", "book.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
