<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Supplement to Chapters 15 and 16 | STA238: Probability, Statistics, and Data Analysis</title>
  <meta name="description" content="This book represents part of the course materials for STA238 at the University of Toronto" />
  <meta name="generator" content="bookdown 0.13 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Supplement to Chapters 15 and 16 | STA238: Probability, Statistics, and Data Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This book represents part of the course materials for STA238 at the University of Toronto" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Supplement to Chapters 15 and 16 | STA238: Probability, Statistics, and Data Analysis" />
  
  <meta name="twitter:description" content="This book represents part of the course materials for STA238 at the University of Toronto" />
  

<meta name="author" content="Alison Gibbs and Alex Stringer" />


<meta name="date" content="2019-12-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="section-supplement-to-chapters-13-and-14.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STA238 University of Toronto</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html"><i class="fa fa-check"></i><b>2</b> Supplement to Chapters 15 and 16</a><ul>
<li class="chapter" data-level="2.1" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-old-faithful"><i class="fa fa-check"></i><b>2.1</b> Old Faithful</a><ul>
<li class="chapter" data-level="2.1.1" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-read-in-the-data"><i class="fa fa-check"></i><b>2.1.1</b> Read in the data</a></li>
<li class="chapter" data-level="2.1.2" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-graphical-summaries"><i class="fa fa-check"></i><b>2.1.2</b> Graphical Summaries</a></li>
<li class="chapter" data-level="2.1.3" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-numerical-summaries-ch-16"><i class="fa fa-check"></i><b>2.1.3</b> Numerical Summaries (Ch 16)</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-drilling"><i class="fa fa-check"></i><b>2.2</b> Drilling</a><ul>
<li class="chapter" data-level="2.2.1" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-read-in-data"><i class="fa fa-check"></i><b>2.2.1</b> Read in data</a></li>
<li class="chapter" data-level="2.2.2" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-graphical-summaries-1"><i class="fa fa-check"></i><b>2.2.2</b> Graphical summaries</a></li>
<li class="chapter" data-level="2.2.3" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-numerical-summaries"><i class="fa fa-check"></i><b>2.2.3</b> Numerical summaries</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-exercises"><i class="fa fa-check"></i><b>2.3</b> Exercises</a></li>
<li class="chapter" data-level="2.4" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-extended-example-smoking-and-age-and-mortality"><i class="fa fa-check"></i><b>2.4</b> Extended example: smoking and age and mortality</a><ul>
<li class="chapter" data-level="2.4.1" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-exercises-1"><i class="fa fa-check"></i><b>2.4.1</b> Exercises</a></li>
<li class="chapter" data-level="2.4.2" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-exercises-2"><i class="fa fa-check"></i><b>2.4.2</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-case-study-rental-housing-in-toronto"><i class="fa fa-check"></i><b>2.5</b> Case study: rental housing in Toronto</a><ul>
<li class="chapter" data-level="2.5.1" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-load-the-data"><i class="fa fa-check"></i><b>2.5.1</b> Load the data</a></li>
<li class="chapter" data-level="2.5.2" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-analysis-i-what-does-the-data-look-like"><i class="fa fa-check"></i><b>2.5.2</b> Analysis I: what does the data look like?</a></li>
<li class="chapter" data-level="2.5.3" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-analysis-ii-do-different-wards-have-different-quality-housing"><i class="fa fa-check"></i><b>2.5.3</b> Analysis II: Do different wards have different quality housing?</a></li>
<li class="chapter" data-level="2.5.4" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-analysis-iii-trends-in-quality-over-time"><i class="fa fa-check"></i><b>2.5.4</b> Analysis III: trends in quality over time</a></li>
<li class="chapter" data-level="2.5.5" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-summary"><i class="fa fa-check"></i><b>2.5.5</b> Summary</a></li>
<li class="chapter" data-level="2.5.6" data-path="section-supplement-to-chapters-15-and-16.html"><a href="section-supplement-to-chapters-15-and-16.html#section-exercises-3"><i class="fa fa-check"></i><b>2.5.6</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="section-supplement-to-chapters-13-and-14.html"><a href="section-supplement-to-chapters-13-and-14.html"><i class="fa fa-check"></i><b>3</b> Supplement to Chapters 13 and 14</a><ul>
<li class="chapter" data-level="3.1" data-path="section-supplement-to-chapters-13-and-14.html"><a href="section-supplement-to-chapters-13-and-14.html#section-law-of-large-numbers-chapter-13"><i class="fa fa-check"></i><b>3.1</b> Law of Large Numbers (Chapter 13)</a><ul>
<li class="chapter" data-level="3.1.1" data-path="section-supplement-to-chapters-13-and-14.html"><a href="section-supplement-to-chapters-13-and-14.html#section-extended-example-the-probability-of-heads"><i class="fa fa-check"></i><b>3.1.1</b> Extended example: the probability of heads</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="section-supplement-to-chapters-13-and-14.html"><a href="section-supplement-to-chapters-13-and-14.html#section-central-limit-theorem-chapter-14"><i class="fa fa-check"></i><b>3.2</b> Central Limit Theorem (Chapter 14)</a><ul>
<li class="chapter" data-level="3.2.1" data-path="section-supplement-to-chapters-13-and-14.html"><a href="section-supplement-to-chapters-13-and-14.html#section-extended-example-the-probability-of-heads-1"><i class="fa fa-check"></i><b>3.2.1</b> Extended example: the probability of heads</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="section-supplement-to-chapters-17-and-19.html"><a href="section-supplement-to-chapters-17-and-19.html"><i class="fa fa-check"></i><b>4</b> Supplement to Chapters 17 and 19</a><ul>
<li class="chapter" data-level="4.1" data-path="section-supplement-to-chapters-17-and-19.html"><a href="section-supplement-to-chapters-17-and-19.html#section-statistical-models-chapter-17"><i class="fa fa-check"></i><b>4.1</b> Statistical models (Chapter 17)</a><ul>
<li class="chapter" data-level="4.1.1" data-path="section-supplement-to-chapters-17-and-19.html"><a href="section-supplement-to-chapters-17-and-19.html#section-janka-hardness-data"><i class="fa fa-check"></i><b>4.1.1</b> Janka Hardness data</a></li>
<li class="chapter" data-level="4.1.2" data-path="section-supplement-to-chapters-17-and-19.html"><a href="section-supplement-to-chapters-17-and-19.html#section-extended-example-ttc-ridership-revenues"><i class="fa fa-check"></i><b>4.1.2</b> Extended example: TTC ridership revenues</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="section-supplement-to-chapters-17-and-19.html"><a href="section-supplement-to-chapters-17-and-19.html#section-unbiased-estimators-chapter-19"><i class="fa fa-check"></i><b>4.2</b> Unbiased Estimators (Chapter 19)</a><ul>
<li class="chapter" data-level="4.2.1" data-path="section-supplement-to-chapters-17-and-19.html"><a href="section-supplement-to-chapters-17-and-19.html#section-simulated-network-data"><i class="fa fa-check"></i><b>4.2.1</b> Simulated network data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="section-supplement-to-chapter-20.html"><a href="section-supplement-to-chapter-20.html"><i class="fa fa-check"></i><b>5</b> Supplement to Chapter 20</a><ul>
<li class="chapter" data-level="5.1" data-path="section-supplement-to-chapter-20.html"><a href="section-supplement-to-chapter-20.html#section-efficiency-and-mean-square-error-chapter-20"><i class="fa fa-check"></i><b>5.1</b> Efficiency and Mean Square Error (Chapter 20)</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="section-supplement-to-evans-rosenthal-section-7-1.html"><a href="section-supplement-to-evans-rosenthal-section-7-1.html"><i class="fa fa-check"></i><b>6</b> Supplement to Evans &amp; Rosenthal Section 7.1</a><ul>
<li class="chapter" data-level="6.1" data-path="section-supplement-to-evans-rosenthal-section-7-1.html"><a href="section-supplement-to-evans-rosenthal-section-7-1.html#section-tutorial"><i class="fa fa-check"></i><b>6.1</b> Tutorial</a><ul>
<li class="chapter" data-level="6.1.1" data-path="section-supplement-to-evans-rosenthal-section-7-1.html"><a href="section-supplement-to-evans-rosenthal-section-7-1.html#section-frequentistlikelihood-perspective"><i class="fa fa-check"></i><b>6.1.1</b> Frequentist/Likelihood Perspective</a></li>
<li class="chapter" data-level="6.1.2" data-path="section-supplement-to-evans-rosenthal-section-7-1.html"><a href="section-supplement-to-evans-rosenthal-section-7-1.html#section-bayesian-inference-introduction"><i class="fa fa-check"></i><b>6.1.2</b> Bayesian Inference: introduction</a></li>
<li class="chapter" data-level="6.1.3" data-path="section-supplement-to-evans-rosenthal-section-7-1.html"><a href="section-supplement-to-evans-rosenthal-section-7-1.html#section-flipping-more-coins"><i class="fa fa-check"></i><b>6.1.3</b> Flipping More Coins</a></li>
<li class="chapter" data-level="6.1.4" data-path="section-supplement-to-evans-rosenthal-section-7-1.html"><a href="section-supplement-to-evans-rosenthal-section-7-1.html#section-visualization"><i class="fa fa-check"></i><b>6.1.4</b> Visualization</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="section-supplement-to-evans-rosenthal-section-7-1.html"><a href="section-supplement-to-evans-rosenthal-section-7-1.html#section-interactive-app"><i class="fa fa-check"></i><b>6.2</b> Interactive App</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="section-supplement-to-chapter-18.html"><a href="section-supplement-to-chapter-18.html"><i class="fa fa-check"></i><b>7</b> Supplement to Chapter 18</a><ul>
<li class="chapter" data-level="7.1" data-path="section-supplement-to-chapter-18.html"><a href="section-supplement-to-chapter-18.html#section-the-bootstrap-chapter-18"><i class="fa fa-check"></i><b>7.1</b> The Bootstrap (Chapter 18)</a><ul>
<li class="chapter" data-level="7.1.1" data-path="section-supplement-to-chapter-18.html"><a href="section-supplement-to-chapter-18.html#section-empirical-bootstrap-old-faithful-data"><i class="fa fa-check"></i><b>7.1.1</b> Empirical bootstrap: Old Faithful data</a></li>
<li class="chapter" data-level="7.1.2" data-path="section-supplement-to-chapter-18.html"><a href="section-supplement-to-chapter-18.html#section-parametric-bootstrap-software-data"><i class="fa fa-check"></i><b>7.1.2</b> Parametric Bootstrap: software data</a></li>
<li class="chapter" data-level="7.1.3" data-path="section-supplement-to-chapter-18.html"><a href="section-supplement-to-chapter-18.html#section-extended-example-the-standard-error-of-a-proportion"><i class="fa fa-check"></i><b>7.1.3</b> Extended example: the standard error of a proportion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="section-supplement-to-chapter-21.html"><a href="section-supplement-to-chapter-21.html"><i class="fa fa-check"></i><b>8</b> Supplement to Chapter 21</a><ul>
<li class="chapter" data-level="8.1" data-path="section-supplement-to-chapter-21.html"><a href="section-supplement-to-chapter-21.html#section-maximum-likelihood-chapter-21"><i class="fa fa-check"></i><b>8.1</b> Maximum Likelihood (Chapter 21)</a><ul>
<li class="chapter" data-level="8.1.1" data-path="section-supplement-to-chapter-21.html"><a href="section-supplement-to-chapter-21.html#section-example-two-coins"><i class="fa fa-check"></i><b>8.1.1</b> Example: two coins</a></li>
<li class="chapter" data-level="8.1.2" data-path="section-supplement-to-chapter-21.html"><a href="section-supplement-to-chapter-21.html#section-example-unknown-coins-n-2"><i class="fa fa-check"></i><b>8.1.2</b> Example: unknown coins, <span class="math inline">\(n = 2\)</span></a></li>
<li class="chapter" data-level="8.1.3" data-path="section-supplement-to-chapter-21.html"><a href="section-supplement-to-chapter-21.html#section-example-unknown-coins-n-bigger-than-2"><i class="fa fa-check"></i><b>8.1.3</b> Example: unknown coins, <span class="math inline">\(n\)</span> bigger than <span class="math inline">\(2\)</span></a></li>
<li class="chapter" data-level="8.1.4" data-path="section-supplement-to-chapter-21.html"><a href="section-supplement-to-chapter-21.html#section-extended-example-rental-housing-in-toronto"><i class="fa fa-check"></i><b>8.1.4</b> Extended example: rental housing in Toronto</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="section-supplement-to-chapter-23-and-24.html"><a href="section-supplement-to-chapter-23-and-24.html"><i class="fa fa-check"></i><b>9</b> Supplement to Chapter 23 and 24</a><ul>
<li class="chapter" data-level="9.1" data-path="section-supplement-to-chapter-23-and-24.html"><a href="section-supplement-to-chapter-23-and-24.html#section-confidence-intervals-for-the-mean-chapter-23"><i class="fa fa-check"></i><b>9.1</b> Confidence Intervals for the Mean (Chapter 23)</a><ul>
<li class="chapter" data-level="9.1.1" data-path="section-supplement-to-chapter-23-and-24.html"><a href="section-supplement-to-chapter-23-and-24.html#section-simulation"><i class="fa fa-check"></i><b>9.1.1</b> Simulation</a></li>
<li class="chapter" data-level="9.1.2" data-path="section-supplement-to-chapter-23-and-24.html"><a href="section-supplement-to-chapter-23-and-24.html#section-gross-calorific-value-measurements-for-osterfeld-262de27"><i class="fa fa-check"></i><b>9.1.2</b> Gross calorific value measurements for Osterfeld 262DE27</a></li>
<li class="chapter" data-level="9.1.3" data-path="section-supplement-to-chapter-23-and-24.html"><a href="section-supplement-to-chapter-23-and-24.html#section-gross-calorific-value-measurements-for-daw-mill-258gb41"><i class="fa fa-check"></i><b>9.1.3</b> Gross calorific value measurements for Daw Mill 258GB41</a></li>
<li class="chapter" data-level="9.1.4" data-path="section-supplement-to-chapter-23-and-24.html"><a href="section-supplement-to-chapter-23-and-24.html#section-bootstrap-confidence-intervals"><i class="fa fa-check"></i><b>9.1.4</b> Bootstrap Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="section-supplement-to-chapter-23-and-24.html"><a href="section-supplement-to-chapter-23-and-24.html#section-more-on-confidence-intervals-chapter-24"><i class="fa fa-check"></i><b>9.2</b> More on confidence intervals (Chapter 24)</a><ul>
<li class="chapter" data-level="9.2.1" data-path="section-supplement-to-chapter-23-and-24.html"><a href="section-supplement-to-chapter-23-and-24.html#section-binomial-distribution"><i class="fa fa-check"></i><b>9.2.1</b> Binomial distribution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="section-extended-example-reasoning-about-goodness-of-fit.html"><a href="section-extended-example-reasoning-about-goodness-of-fit.html"><i class="fa fa-check"></i><b>10</b> Extended Example: Reasoning About Goodness of Fit</a><ul>
<li class="chapter" data-level="10.1" data-path="section-extended-example-reasoning-about-goodness-of-fit.html"><a href="section-extended-example-reasoning-about-goodness-of-fit.html#section-go-and-read-the-blog-post"><i class="fa fa-check"></i><b>10.1</b> Go and read the blog post</a></li>
<li class="chapter" data-level="10.2" data-path="section-extended-example-reasoning-about-goodness-of-fit.html"><a href="section-extended-example-reasoning-about-goodness-of-fit.html#section-distribution-of-last-digits"><i class="fa fa-check"></i><b>10.2</b> Distribution of last digits</a><ul>
<li class="chapter" data-level="10.2.1" data-path="section-extended-example-reasoning-about-goodness-of-fit.html"><a href="section-extended-example-reasoning-about-goodness-of-fit.html#section-read-in-the-data-1"><i class="fa fa-check"></i><b>10.2.1</b> Read in the data</a></li>
<li class="chapter" data-level="10.2.2" data-path="section-extended-example-reasoning-about-goodness-of-fit.html"><a href="section-extended-example-reasoning-about-goodness-of-fit.html#section-make-the-histogram"><i class="fa fa-check"></i><b>10.2.2</b> Make the histogram</a></li>
<li class="chapter" data-level="10.2.3" data-path="section-extended-example-reasoning-about-goodness-of-fit.html"><a href="section-extended-example-reasoning-about-goodness-of-fit.html#section-testing-goodness-of-fit-simulation"><i class="fa fa-check"></i><b>10.2.3</b> Testing goodness of fit: simulation</a></li>
<li class="chapter" data-level="10.2.4" data-path="section-extended-example-reasoning-about-goodness-of-fit.html"><a href="section-extended-example-reasoning-about-goodness-of-fit.html#section-testing-goodness-of-fit-math"><i class="fa fa-check"></i><b>10.2.4</b> Testing goodness of fit: math</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="section-supplement-to-evans-rosenthal-section-7-2.html"><a href="section-supplement-to-evans-rosenthal-section-7-2.html"><i class="fa fa-check"></i><b>11</b> Supplement to Evans &amp; Rosenthal Section 7.2</a><ul>
<li class="chapter" data-level="11.1" data-path="section-supplement-to-evans-rosenthal-section-7-2.html"><a href="section-supplement-to-evans-rosenthal-section-7-2.html#section-estimation-in-bayesian-inference-general-ideas"><i class="fa fa-check"></i><b>11.1</b> Estimation in Bayesian Inference: general ideas</a><ul>
<li class="chapter" data-level="11.1.1" data-path="section-supplement-to-evans-rosenthal-section-7-2.html"><a href="section-supplement-to-evans-rosenthal-section-7-2.html#section-the-prior"><i class="fa fa-check"></i><b>11.1.1</b> The Prior</a></li>
<li class="chapter" data-level="11.1.2" data-path="section-supplement-to-evans-rosenthal-section-7-2.html"><a href="section-supplement-to-evans-rosenthal-section-7-2.html#section-the-posterior"><i class="fa fa-check"></i><b>11.1.2</b> The Posterior</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="section-supplement-to-evans-rosenthal-section-7-2.html"><a href="section-supplement-to-evans-rosenthal-section-7-2.html#section-estimation-in-bayesian-inference-point-and-interval-estimation"><i class="fa fa-check"></i><b>11.2</b> Estimation in Bayesian Inference: point and interval estimation</a></li>
<li class="chapter" data-level="11.3" data-path="section-supplement-to-evans-rosenthal-section-7-2.html"><a href="section-supplement-to-evans-rosenthal-section-7-2.html#section-choosing-a-prior"><i class="fa fa-check"></i><b>11.3</b> Choosing a Prior</a><ul>
<li class="chapter" data-level="11.3.1" data-path="section-supplement-to-evans-rosenthal-section-7-2.html"><a href="section-supplement-to-evans-rosenthal-section-7-2.html#section-conjugate-priors"><i class="fa fa-check"></i><b>11.3.1</b> Conjugate Priors</a></li>
<li class="chapter" data-level="11.3.2" data-path="section-supplement-to-evans-rosenthal-section-7-2.html"><a href="section-supplement-to-evans-rosenthal-section-7-2.html#section-setting-hyperparameters-by-moment-matching"><i class="fa fa-check"></i><b>11.3.2</b> Setting Hyperparameters by moment-matching</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="section-predictive-modelling.html"><a href="section-predictive-modelling.html"><i class="fa fa-check"></i><b>12</b> Predictive Modelling</a><ul>
<li class="chapter" data-level="12.1" data-path="section-predictive-modelling.html"><a href="section-predictive-modelling.html#section-overview"><i class="fa fa-check"></i><b>12.1</b> Overview</a></li>
<li class="chapter" data-level="12.2" data-path="section-predictive-modelling.html"><a href="section-predictive-modelling.html#section-plug-in-prediction-coin-flipping"><i class="fa fa-check"></i><b>12.2</b> Plug-in prediction: coin flipping</a></li>
<li class="chapter" data-level="12.3" data-path="section-predictive-modelling.html"><a href="section-predictive-modelling.html#section-bayesian-prediction-coin-flipping"><i class="fa fa-check"></i><b>12.3</b> Bayesian Prediction: coin flipping</a></li>
<li class="chapter" data-level="12.4" data-path="section-predictive-modelling.html"><a href="section-predictive-modelling.html#section-extended-example-income-and-advertsing-datasets"><i class="fa fa-check"></i><b>12.4</b> Extended example: Income and Advertsing datasets</a></li>
<li class="chapter" data-level="12.5" data-path="section-predictive-modelling.html"><a href="section-predictive-modelling.html#section-extended-example-predicting-call-centre-wait-times"><i class="fa fa-check"></i><b>12.5</b> Extended example: predicting call centre wait times</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="section-installing-r-and-rstudio.html"><a href="section-installing-r-and-rstudio.html"><i class="fa fa-check"></i><b>13</b> Installing R and RStudio</a><ul>
<li class="chapter" data-level="13.1" data-path="section-installing-r-and-rstudio.html"><a href="section-installing-r-and-rstudio.html#section-installing-r"><i class="fa fa-check"></i><b>13.1</b> Installing R</a></li>
<li class="chapter" data-level="13.2" data-path="section-installing-r-and-rstudio.html"><a href="section-installing-r-and-rstudio.html#section-installing-rstudio"><i class="fa fa-check"></i><b>13.2</b> Installing RStudio</a></li>
<li class="chapter" data-level="13.3" data-path="section-installing-r-and-rstudio.html"><a href="section-installing-r-and-rstudio.html#section-using-rmarkdown"><i class="fa fa-check"></i><b>13.3</b> Using RMarkdown</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STA238: Probability, Statistics, and Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="section-supplement-to-chapters-15-and-16" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Supplement to Chapters 15 and 16</h1>
<p>This chapter implements much of the analysis shown in chapters 15 and 16 of
A Modern Introduction to Probability and Statistics (MIPS). R code is given for the
simple textbook datasets used in the book, and then the concepts are
illustrated on real data.</p>
<p>All datasets from the book can be downloaded here: <a href="https://www.tudelft.nl/en/eemcs/the-faculty/departments/applied-mathematics/applied-probability/education/mips/" class="uri">https://www.tudelft.nl/en/eemcs/the-faculty/departments/applied-mathematics/applied-probability/education/mips/</a>.</p>
<p>The assigned exercises associated with this material are from MIPS, as follows: 15.1, 15.2; 15.5; 15.6; 15.8; 15.11; 15.12
16.1, 16.2; 16.3; 16.4, 16.5; 16.6; 16.8; 16.15. Answers to selected exercises are in the
back of the book. You should also do all the “quick exercises” within chapters 15 and 16
(solutions are at the end of the chapter). Use <code>R</code> as much as possible when answering the
questions.</p>
<div id="section-old-faithful" class="section level2">
<h2><span class="header-section-number">2.1</span> Old Faithful</h2>
<p>The Old Faithful data is stored in the <code>oldfaithful.txt</code> file in the book data
folder. To read it in to <code>R</code>, first you need to look at its contents.</p>
<div id="section-read-in-the-data" class="section level3">
<h3><span class="header-section-number">2.1.1</span> Read in the data</h3>
<p>You can either open it in a text editor (since it’s small), or print out the
first few lines on the command line. The latter is nicer: the data is printed
properly, without added bits from notepad or whatever; and if you’re working with
large data stored in big text files, trying to open the whole thing in an editor
will crash your computer. It’s good to get in the habit of working a bit on the
command line now.</p>
<p>If you have
a Mac or Linux-based system, open a terminal. If you have a Windows based system,
get a Mac or Linux. Just kidding (not really though). Download Git Bash: <a href="https://git-scm.com/download/win" class="uri">https://git-scm.com/download/win</a>
and open a new terminal window.</p>
<p>To look at a text file on the command line, use the <code>head</code> command. You have to
tell it where to look on your computer. You can navigate to the folder where the
data is stored and just type the name of the file, or you can type a whole filepath,
or a relative filepath. Right now, I am in the working directory for this book,
and relative to this location, the data is stored in <code>data/MIPSdata</code>.</p>
<p>If you are
not in this directory, you have to navigate there. The <code>pwd</code> command tells you
where you are, the <code>ls -l</code> command tells you what’s there, and the <code>cd</code> command
lets you change to a new directory. So if you’re in <code>/home/alex</code>, you would type
<code>pwd</code> and it would print <code>/home/alex</code>. If this location contains a folder called
<code>data</code>, you can type <code>ls -l</code> and there should be a list of stuff, including a folder
called <code>data</code>. You can type <code>cd data</code> to go there, and repeat the process. Navigate
to where you downloaded the data to– it’s kind of like a game!</p>
<p>Anyways, once you’re there, type:</p>
<div class="sourceCode" id="section-cb1"><pre class="sourceCode bash"><code class="sourceCode bash"><a class="sourceLine" id="cb1-1" title="1"><span class="fu">head</span> data/MIPSdata/oldfaithful.txt</a></code></pre></div>
<pre><code>## 216  
## 108  
## 200  
## 137  
## 272  
## 173  
## 282  
## 216  
## 117  
## 261 </code></pre>
<p>Don’t worry if you don’t see the <code>\#\#</code>; those are
added by the book. I don’t see them when I do this right in the command line.</p>
<p>A column of numbers is printed. This indicates that the text file <code>oldfaithdful.txt</code>
contains a single column of numbers, and no header row. A header row is what it’s
called when the first row of the dataset contains the names of the columns.</p>
<p>To read such a dataset into <code>R</code>, we’ll use the <code>read_csv</code> function in the <code>readr</code>
package. The <code>readr</code> package is automatically loaded when we load the <code>tidyverse</code>
package. If this sentence is confusing (no worries!) I recommend you check out
<a href="https://awstringer1.github.io/ssu-r-workshop/ssu-r-workshop.html">my R tutorial</a>.</p>
<p>We’ll just do that:</p>
<div class="sourceCode" id="section-cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb3-2" title="2">oldfaithful &lt;-<span class="st"> </span>readr<span class="op">::</span><span class="kw">read_csv</span>(</a>
<a class="sourceLine" id="cb3-3" title="3">  <span class="dt">file =</span> <span class="st">&quot;data/MIPSdata/oldfaithful.txt&quot;</span>, <span class="co"># Tell it where the file is</span></a>
<a class="sourceLine" id="cb3-4" title="4">  <span class="dt">col_names =</span> <span class="st">&quot;time&quot;</span>, <span class="co"># Tell it that the first row is NOT column names, and at the same time, tell it what name you want for the column.</span></a>
<a class="sourceLine" id="cb3-5" title="5">  <span class="dt">col_types =</span> <span class="st">&quot;n&quot;</span> <span class="co"># Tell it that there is one column, and it is &quot;numeric&quot; (n)</span></a>
<a class="sourceLine" id="cb3-6" title="6">)</a>
<a class="sourceLine" id="cb3-7" title="7"><span class="co"># Check what was read in using the dplyr::glimpse() function</span></a>
<a class="sourceLine" id="cb3-8" title="8">dplyr<span class="op">::</span><span class="kw">glimpse</span>(oldfaithful)</a></code></pre></div>
<pre><code>## Observations: 272
## Variables: 1
## $ time [3m[38;5;246m&lt;dbl&gt;[39m[23m 216, 108, 200, 137, 272, 173, 282, 216, 117, 261, 110, 235,…</code></pre>
<p>By <code>glimpse</code>ing the data, we see that the format matches what we saw in the raw
file, and we are given the number of rows too. Check that the number of rows matches
what was in the raw file by printing out the number of rows on the command line
using the <code>wc -l</code> command (“wc” = “word count” and “-l” means count “lines”):</p>
<div class="sourceCode" id="section-cb5"><pre class="sourceCode bash"><code class="sourceCode bash"><a class="sourceLine" id="cb5-1" title="1"><span class="fu">wc</span> -l data/MIPSdata/oldfaithful.txt</a></code></pre></div>
<pre><code>##      271 data/MIPSdata/oldfaithful.txt</code></pre>
<p>What happened, why don’t they match? They do. The <code>wc -l</code> command actually counts
the number of “newline” characters in the file. It is customary to end a data file
with a newline character. This file doesn’t, though. How do I know? Type the following:</p>
<div class="sourceCode" id="section-cb7"><pre class="sourceCode bash"><code class="sourceCode bash"><a class="sourceLine" id="cb7-1" title="1"><span class="fu">tail</span> data/MIPSdata/oldfaithful.txt</a></code></pre></div>
<pre><code>## 111  
## 255  
## 119  
## 135  
## 285  
## 247  
## 129  
## 265
## 109  
## 268</code></pre>
<p>This prints out the last few lines of the file. In this book, these are printed
as normal. But if you do it on the command line, you’ll see that the command
prompt gets printed on the same line as the final number, <code>268</code>. This indicates
that the file does not end with a newline character, and hence the total number
of newlines in the file is <code>271</code>, corresponding to <code>272</code> actual lines of data.</p>
<p><strong>Remark</strong>: subtle issues like this come up all the time in data analysis. The
only way to get good at it is practice, so don’t be discouraged!</p>
</div>
<div id="section-graphical-summaries" class="section level3">
<h3><span class="header-section-number">2.1.2</span> Graphical Summaries</h3>
<p>Now that the data has been read in and checked, we can realize the fruits of
our labour! Chapter 15 analyzes these data using a tabular display, histogram, kernel density
estimate, and empirical CDF. Here is how to do these things in <code>R</code>.</p>
<div class="sourceCode" id="section-cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1"><span class="co"># Tabular display</span></a>
<a class="sourceLine" id="cb9-2" title="2"><span class="kw">print</span>(oldfaithful<span class="op">$</span>time)</a></code></pre></div>
<pre><code>##   [1] 216 108 200 137 272 173 282 216 117 261 110 235 252 105 282 130 105
##  [18] 288  96 255 108 105 207 184 272 216 118 245 231 266 258 268 202 242
##  [35] 230 121 112 290 110 287 261 113 274 105 272 199 230 126 278 120 288
##  [52] 283 110 290 104 293 223 100 274 259 134 270 105 288 109 264 250 282
##  [69] 124 282 242 118 270 240 119 304 121 274 233 216 248 260 246 158 244
##  [86] 296 237 271 130 240 132 260 112 289 110 258 280 225 112 294 149 262
## [103] 126 270 243 112 282 107 291 221 284 138 294 265 102 278 139 276 109
## [120] 265 157 244 255 118 276 226 115 270 136 279 112 250 168 260 110 263
## [137] 113 296 122 224 254 134 272 289 260 119 278 121 306 108 302 240 144
## [154] 276 214 240 270 245 108 238 132 249 120 230 210 275 142 300 116 277
## [171] 115 125 275 200 250 260 270 145 240 250 113 275 255 226 122 266 245
## [188] 110 265 131 288 110 288 246 238 254 210 262 135 280 126 261 248 112
## [205] 276 107 262 231 116 270 143 282 112 230 205 254 144 288 120 249 112
## [222] 256 105 269 240 247 245 256 235 273 245 145 251 133 267 113 111 257
## [239] 237 140 249 141 296 174 275 230 125 262 128 261 132 267 214 270 249
## [256] 229 235 267 120 257 286 272 111 255 119 135 285 247 129 265 109 268</code></pre>
<div class="sourceCode" id="section-cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1"><span class="co"># Ugly! You can use the View() function to open the data in a spreadsheet</span></a>
<a class="sourceLine" id="cb11-2" title="2"><span class="co"># Not run:</span></a>
<a class="sourceLine" id="cb11-3" title="3"><span class="co"># View(oldfaithful)</span></a>
<a class="sourceLine" id="cb11-4" title="4"></a>
<a class="sourceLine" id="cb11-5" title="5"><span class="co"># Histogram using base R</span></a>
<a class="sourceLine" id="cb11-6" title="6"><span class="kw">hist</span>(oldfaithful<span class="op">$</span>time)</a></code></pre></div>
<p><img src="book_files/figure-html/oldfaithful-analysis-1-1.png" width="672" /></p>
<div class="sourceCode" id="section-cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1"><span class="co"># Base R graphics are outdated. Use ggplot2, which is loaded automatically with the tidyverse:</span></a>
<a class="sourceLine" id="cb12-2" title="2">oldfaithful <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb12-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> time)) <span class="op">+</span></a>
<a class="sourceLine" id="cb12-4" title="4"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb12-5" title="5"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y =</span> ..density..),<span class="dt">bins =</span> <span class="dv">30</span>,<span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>,<span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>,<span class="dt">alpha =</span> <span class="fl">.3</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb12-6" title="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Eruption times for Old Faithful geyser&quot;</span>,</a>
<a class="sourceLine" id="cb12-7" title="7">       <span class="dt">x =</span> <span class="st">&quot;Eruption time&quot;</span>,</a>
<a class="sourceLine" id="cb12-8" title="8">       <span class="dt">y =</span> <span class="st">&quot;Density&quot;</span>)</a></code></pre></div>
<p><img src="book_files/figure-html/oldfaithful-analysis-1-2.png" width="672" /></p>
<div class="sourceCode" id="section-cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1"><span class="co"># Try different numbers of bins and you might see different patterns. Do you think this is a</span></a>
<a class="sourceLine" id="cb13-2" title="2"><span class="co"># good or bad thing, or both?</span></a>
<a class="sourceLine" id="cb13-3" title="3"><span class="co"># Their &quot;optimal&quot; bin width:</span></a>
<a class="sourceLine" id="cb13-4" title="4">s &lt;-<span class="st"> </span><span class="kw">sd</span>(oldfaithful<span class="op">$</span>time)</a>
<a class="sourceLine" id="cb13-5" title="5">n &lt;-<span class="st"> </span><span class="kw">nrow</span>(oldfaithful)</a>
<a class="sourceLine" id="cb13-6" title="6">b &lt;-<span class="st"> </span>(<span class="dv">24</span><span class="op">*</span><span class="kw">sqrt</span>(pi))<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>) <span class="op">*</span><span class="st"> </span>s <span class="op">*</span><span class="st"> </span>(n<span class="op">^</span>(<span class="op">-</span><span class="dv">1</span><span class="op">/</span><span class="dv">3</span>))</a>
<a class="sourceLine" id="cb13-7" title="7">b</a></code></pre></div>
<pre><code>## [1] 36.89694</code></pre>
<div class="sourceCode" id="section-cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1">oldfaithful <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb15-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> time)) <span class="op">+</span></a>
<a class="sourceLine" id="cb15-3" title="3"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb15-4" title="4"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y =</span> ..density..),<span class="dt">bins =</span> <span class="kw">round</span>(b),<span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>,<span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>,<span class="dt">alpha =</span> <span class="fl">.3</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb15-5" title="5"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Eruption times for Old Faithful geyser&quot;</span>,</a>
<a class="sourceLine" id="cb15-6" title="6">       <span class="dt">subtitle =</span> stringr<span class="op">::</span><span class="kw">str_c</span>(<span class="st">&quot;&#39;Optimal&#39; bin width of b = &quot;</span>,<span class="kw">round</span>(b)),</a>
<a class="sourceLine" id="cb15-7" title="7">       <span class="dt">x =</span> <span class="st">&quot;Eruption time&quot;</span>,</a>
<a class="sourceLine" id="cb15-8" title="8">       <span class="dt">y =</span> <span class="st">&quot;Density&quot;</span>)</a></code></pre></div>
<p><img src="book_files/figure-html/oldfaithful-analysis-1-3.png" width="672" /></p>
<p>To get kernel density estimates, there are a couple different ways. The <code>density</code>
function in <code>R</code> does the math for you, using a Gaussian kernel (the functions <span class="math inline">\(K_{i}\)</span>
are taken to be Gaussian density functions with mean and standard deviation
determined by the data). You can plot the output of <code>density</code> using base <code>R</code> or
<code>ggplot</code>. You can also use the <code>ggplot</code> <code>geom_density</code> function to do something
similar automatically.</p>
<div class="sourceCode" id="section-cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1"><span class="co"># Kernel density estimation in R</span></a>
<a class="sourceLine" id="cb16-2" title="2">dens &lt;-<span class="st"> </span><span class="kw">density</span>(oldfaithful<span class="op">$</span>time)</a>
<a class="sourceLine" id="cb16-3" title="3">dens</a></code></pre></div>
<pre><code>## 
## Call:
##  density.default(x = oldfaithful$time)
## 
## Data: oldfaithful$time (272 obs.);   Bandwidth &#39;bw&#39; = 20.09
## 
##        x                y            
##  Min.   : 35.74   Min.   :3.771e-06  
##  1st Qu.:118.37   1st Qu.:8.571e-04  
##  Median :201.00   Median :2.412e-03  
##  Mean   :201.00   Mean   :3.022e-03  
##  3rd Qu.:283.63   3rd Qu.:5.143e-03  
##  Max.   :366.26   Max.   :8.070e-03</code></pre>
<div class="sourceCode" id="section-cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1"><span class="kw">plot</span>(dens)</a></code></pre></div>
<p><img src="book_files/figure-html/oldfaithfulanalysis-2-1.png" width="672" /></p>
<div class="sourceCode" id="section-cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1"><span class="co"># Okay... ggplot?</span></a>
<a class="sourceLine" id="cb19-2" title="2"><span class="kw">tibble</span>(<span class="dt">x =</span> dens<span class="op">$</span>x,<span class="dt">y =</span> dens<span class="op">$</span>y) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb19-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x,<span class="dt">y =</span> y)) <span class="op">+</span></a>
<a class="sourceLine" id="cb19-4" title="4"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb19-5" title="5"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb19-6" title="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Kernel density estimate, Old Faithful data&quot;</span>,</a>
<a class="sourceLine" id="cb19-7" title="7">       <span class="dt">subtitle =</span> <span class="st">&quot;Manually-calculated values&quot;</span>,</a>
<a class="sourceLine" id="cb19-8" title="8">       <span class="dt">x =</span> <span class="st">&quot;Eruption time&quot;</span>,</a>
<a class="sourceLine" id="cb19-9" title="9">       <span class="dt">y =</span> <span class="st">&quot;Density&quot;</span>)</a></code></pre></div>
<p><img src="book_files/figure-html/oldfaithfulanalysis-2-2.png" width="672" /></p>
<div class="sourceCode" id="section-cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1"><span class="co"># Can also do automatically:</span></a>
<a class="sourceLine" id="cb20-2" title="2">oldfaithful <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb20-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> time)) <span class="op">+</span></a>
<a class="sourceLine" id="cb20-4" title="4"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb20-5" title="5"><span class="st">  </span><span class="kw">geom_density</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb20-6" title="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Kernel density estimate, Old Faithful data&quot;</span>,</a>
<a class="sourceLine" id="cb20-7" title="7">       <span class="dt">subtitle =</span> <span class="st">&quot;Automatically-calculated values&quot;</span>,</a>
<a class="sourceLine" id="cb20-8" title="8">       <span class="dt">x =</span> <span class="st">&quot;Eruption time&quot;</span>,</a>
<a class="sourceLine" id="cb20-9" title="9">       <span class="dt">y =</span> <span class="st">&quot;Density&quot;</span>)</a></code></pre></div>
<p><img src="book_files/figure-html/oldfaithfulanalysis-2-3.png" width="672" /></p>
<div class="sourceCode" id="section-cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1"><span class="co"># The reason to manually calculate the values is because you have more control.</span></a>
<a class="sourceLine" id="cb21-2" title="2"><span class="co"># I don&#39;t know what&#39;s happening at the endpoints there, and it&#39;s too much work</span></a>
<a class="sourceLine" id="cb21-3" title="3"><span class="co"># to go and figure out how to make ggplot not do that.</span></a>
<a class="sourceLine" id="cb21-4" title="4"><span class="co"># When you calculate the plotting values yourself and then put them into ggplot,</span></a>
<a class="sourceLine" id="cb21-5" title="5"><span class="co"># you have total control!</span></a></code></pre></div>
<p>For the empirical distribution function, we use the <code>ecdf</code> function in <code>R</code>. You
would think this function should behave in a similar manner to the <code>density</code> function,
but it doesn’t. It returns a function which computes the ecdf. It still has a <code>plot</code>
method, but to use it with <code>ggplot</code> we have to use <code>stat_function</code>:</p>
<div class="sourceCode" id="section-cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" title="1">faithful_ecdf &lt;-<span class="st"> </span><span class="kw">ecdf</span>(oldfaithful<span class="op">$</span>time)</a>
<a class="sourceLine" id="cb22-2" title="2"><span class="kw">plot</span>(faithful_ecdf)</a></code></pre></div>
<p><img src="book_files/figure-html/oldfaithfulanalysis-3-1.png" width="672" /></p>
<div class="sourceCode" id="section-cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1"><span class="co"># ggplot</span></a>
<a class="sourceLine" id="cb23-2" title="2"><span class="kw">tibble</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="dv">100</span>,<span class="dv">300</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Tell ggplot we want to plot the ecdf from 100 to 300</span></a>
<a class="sourceLine" id="cb23-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x)) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-4" title="4"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb23-5" title="5"><span class="st">  </span><span class="kw">stat_function</span>(<span class="dt">fun =</span> faithful_ecdf) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-6" title="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Empirical CDF for Old Faithful Eruption Times&quot;</span>,</a>
<a class="sourceLine" id="cb23-7" title="7">       <span class="dt">x =</span> <span class="st">&quot;Eruption Time&quot;</span>,</a>
<a class="sourceLine" id="cb23-8" title="8">       <span class="dt">y =</span> <span class="st">&quot;Empirical probability that an eruption time is less than x&quot;</span>)</a></code></pre></div>
<p><img src="book_files/figure-html/oldfaithfulanalysis-3-2.png" width="672" /></p>
<p><strong>Discussion point</strong>: the CDF is the integrated pdf:
<span class="math display">\[
F(x) = \int_{-\infty}^{x}f(s)ds
\]</span>
So why don’t we integrate the kernel density estimate to get the empirical CDF?
One of the great benefits of taking a computation-forward approach to statistical
inference is that we can “shoot first and ask questions later”- just try it, and
then (maybe) use math to explain the results.</p>
<p>Here is the world’s most naive numerical integration-based estimate of a CDF:</p>
<div class="sourceCode" id="section-cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1"><span class="kw">tibble</span>(</a>
<a class="sourceLine" id="cb24-2" title="2">  <span class="dt">x =</span> dens<span class="op">$</span>x[<span class="op">-</span><span class="dv">1</span>],</a>
<a class="sourceLine" id="cb24-3" title="3">  <span class="dt">y =</span> <span class="kw">cumsum</span>(dens<span class="op">$</span>y[<span class="op">-</span><span class="dv">1</span>]) <span class="op">*</span><span class="st"> </span><span class="kw">diff</span>(dens<span class="op">$</span>x) <span class="co"># Quick and dirty numerical integration. Can you put something better?</span></a>
<a class="sourceLine" id="cb24-4" title="4">) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb24-5" title="5"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x,<span class="dt">y =</span> y)) <span class="op">+</span></a>
<a class="sourceLine" id="cb24-6" title="6"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb24-7" title="7"><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb24-8" title="8"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Numerical integration-based empirical CDF for Old Faithful data&quot;</span>,</a>
<a class="sourceLine" id="cb24-9" title="9">       <span class="dt">x =</span> <span class="st">&quot;Eruption time&quot;</span>,</a>
<a class="sourceLine" id="cb24-10" title="10">       <span class="dt">y =</span> <span class="st">&quot;Empirical probability that an eruption time is less than x&quot;</span>)</a></code></pre></div>
<p><img src="book_files/figure-html/oldfaithfulanalysis-4-1.png" width="672" /></p>
<p>What do you think? Is this better, worse, or just different than the ECDF?</p>
<p>Chapter 16 discusses boxplots. To get a boxplot, again, you can use base <code>R</code> or <code>ggplot</code>.
We have:</p>
<div class="sourceCode" id="section-cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1"><span class="co"># Base R</span></a>
<a class="sourceLine" id="cb25-2" title="2"><span class="kw">boxplot</span>(oldfaithful<span class="op">$</span>time)</a></code></pre></div>
<p><img src="book_files/figure-html/oldfaithful-boxplot-1-1.png" width="672" /></p>
<div class="sourceCode" id="section-cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" title="1"><span class="co"># ggplot</span></a>
<a class="sourceLine" id="cb26-2" title="2">oldfaithful <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb26-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> time)) <span class="op">+</span></a>
<a class="sourceLine" id="cb26-4" title="4"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb26-5" title="5"><span class="st">  </span><span class="kw">geom_boxplot</span>(<span class="dt">width =</span> <span class="fl">.1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb26-6" title="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Boxplot of eruption times, Old Faithful data&quot;</span>,</a>
<a class="sourceLine" id="cb26-7" title="7">       <span class="dt">y =</span> <span class="st">&quot;Eruption time&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb26-8" title="8"><span class="st">  </span><span class="co"># Have to play around with the x axis to get it to look nice *shrug*</span></a>
<a class="sourceLine" id="cb26-9" title="9"><span class="st">  </span><span class="kw">coord_cartesian</span>(<span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span>.<span class="dv">2</span>,.<span class="dv">2</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb26-10" title="10"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_blank</span>())</a></code></pre></div>
<p><img src="book_files/figure-html/oldfaithful-boxplot-1-2.png" width="672" /></p>
</div>
<div id="section-numerical-summaries-ch-16" class="section level3">
<h3><span class="header-section-number">2.1.3</span> Numerical Summaries (Ch 16)</h3>
<p>The numerical summaries in chapter 16 include the sample mean and median, sample
standard deviation and mean absolute deviation, and quantiles.</p>
<div class="sourceCode" id="section-cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" title="1"><span class="co"># Mean</span></a>
<a class="sourceLine" id="cb27-2" title="2"><span class="kw">mean</span>(oldfaithful<span class="op">$</span>time)</a></code></pre></div>
<pre><code>## [1] 209.2684</code></pre>
<div class="sourceCode" id="section-cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" title="1"><span class="co"># Median</span></a>
<a class="sourceLine" id="cb29-2" title="2"><span class="kw">median</span>(oldfaithful<span class="op">$</span>time)</a></code></pre></div>
<pre><code>## [1] 240</code></pre>
<div class="sourceCode" id="section-cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" title="1"><span class="co"># Standard deviation</span></a>
<a class="sourceLine" id="cb31-2" title="2"><span class="kw">sd</span>(oldfaithful<span class="op">$</span>time)</a></code></pre></div>
<pre><code>## [1] 68.48329</code></pre>
<div class="sourceCode" id="section-cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" title="1"><span class="co"># Quantiles: tell it which ones you want. I want 0, 25, 50, 75, 100</span></a>
<a class="sourceLine" id="cb33-2" title="2"><span class="kw">quantile</span>(oldfaithful<span class="op">$</span>time,<span class="dt">probs =</span> <span class="kw">c</span>(<span class="dv">0</span>,.<span class="dv">25</span>,.<span class="dv">50</span>,.<span class="dv">75</span>,<span class="fl">1.00</span>))</a></code></pre></div>
<pre><code>##     0%    25%    50%    75%   100% 
##  96.00 129.75 240.00 267.25 306.00</code></pre>
<div class="sourceCode" id="section-cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" title="1"><span class="co"># The zeroth and hundredth quantiles are the sample minimum and maximum:</span></a>
<a class="sourceLine" id="cb35-2" title="2"><span class="kw">min</span>(oldfaithful<span class="op">$</span>time)</a></code></pre></div>
<pre><code>## [1] 96</code></pre>
<div class="sourceCode" id="section-cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" title="1"><span class="kw">max</span>(oldfaithful<span class="op">$</span>time)</a></code></pre></div>
<pre><code>## [1] 306</code></pre>
<div class="sourceCode" id="section-cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" title="1"><span class="co"># Actually, you can get all this with the summary() function:</span></a>
<a class="sourceLine" id="cb39-2" title="2"><span class="kw">summary</span>(oldfaithful<span class="op">$</span>time)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    96.0   129.8   240.0   209.3   267.2   306.0</code></pre>
<div class="sourceCode" id="section-cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" title="1"><span class="co"># Mean absolute deviation</span></a>
<a class="sourceLine" id="cb41-2" title="2"><span class="co"># I don&#39;t know an R function for this off the top of my head (maybe you can find one?)</span></a>
<a class="sourceLine" id="cb41-3" title="3"><span class="co"># So let&#39;s calculate it manually.</span></a>
<a class="sourceLine" id="cb41-4" title="4"><span class="co"># Actually, let&#39;s calculate them ALL manually!</span></a>
<a class="sourceLine" id="cb41-5" title="5"><span class="co"># Mean:</span></a>
<a class="sourceLine" id="cb41-6" title="6"><span class="kw">sum</span>(oldfaithful<span class="op">$</span>time) <span class="op">/</span><span class="st"> </span><span class="kw">length</span>(oldfaithful<span class="op">$</span>time)</a></code></pre></div>
<pre><code>## [1] 209.2684</code></pre>
<div class="sourceCode" id="section-cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1"><span class="co"># Median: it&#39;s the 50th percentile</span></a>
<a class="sourceLine" id="cb43-2" title="2"><span class="kw">quantile</span>(oldfaithful<span class="op">$</span>time,<span class="dt">probs =</span> <span class="fl">.5</span>)</a></code></pre></div>
<pre><code>## 50% 
## 240</code></pre>
<div class="sourceCode" id="section-cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1"><span class="co"># Can get it manually too:</span></a>
<a class="sourceLine" id="cb45-2" title="2"><span class="kw">sort</span>(oldfaithful<span class="op">$</span>time)[<span class="kw">length</span>(oldfaithful<span class="op">$</span>time)<span class="op">/</span><span class="dv">2</span>]</a></code></pre></div>
<pre><code>## [1] 240</code></pre>
<div class="sourceCode" id="section-cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1"><span class="co"># Better to use the quantile() function though.</span></a>
<a class="sourceLine" id="cb47-2" title="2"><span class="co"># Standard deviation. Need to save the mean to a variable first:</span></a>
<a class="sourceLine" id="cb47-3" title="3">mn &lt;-<span class="st"> </span><span class="kw">mean</span>(oldfaithful<span class="op">$</span>time)</a>
<a class="sourceLine" id="cb47-4" title="4"><span class="kw">sqrt</span>( <span class="kw">sum</span>( (oldfaithful<span class="op">$</span>time <span class="op">-</span><span class="st"> </span>mn)<span class="op">^</span><span class="dv">2</span> ) <span class="op">/</span><span class="st"> </span>( <span class="kw">length</span>(oldfaithful<span class="op">$</span>time) <span class="op">-</span><span class="st"> </span><span class="dv">1</span> ) )</a></code></pre></div>
<pre><code>## [1] 68.48329</code></pre>
<div class="sourceCode" id="section-cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1"><span class="co"># MAD. Similar to sd:</span></a>
<a class="sourceLine" id="cb49-2" title="2">md &lt;-<span class="st"> </span><span class="kw">median</span>(oldfaithful<span class="op">$</span>time)</a>
<a class="sourceLine" id="cb49-3" title="3"><span class="kw">median</span>( <span class="kw">abs</span>(oldfaithful<span class="op">$</span>time <span class="op">-</span><span class="st"> </span>md) )</a></code></pre></div>
<pre><code>## [1] 38.5</code></pre>
<div class="sourceCode" id="section-cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1"><span class="co"># IQR:</span></a>
<a class="sourceLine" id="cb51-2" title="2"><span class="kw">quantile</span>(oldfaithful<span class="op">$</span>time,<span class="dt">probs =</span> <span class="fl">.75</span>) <span class="op">-</span><span class="st"> </span><span class="kw">quantile</span>(oldfaithful<span class="op">$</span>time,<span class="dt">probs =</span> <span class="fl">.25</span>)</a></code></pre></div>
<pre><code>##   75% 
## 137.5</code></pre>
<div class="sourceCode" id="section-cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1"><span class="co"># Note that there are various ways to correct for the fact that not all quantiles</span></a>
<a class="sourceLine" id="cb53-2" title="2"><span class="co"># are exact (you may not have a datapoint which has EXACTLY 25% of the data below it,</span></a>
<a class="sourceLine" id="cb53-3" title="3"><span class="co"># like if the sample size isn&#39;t divisible by 4). R probably uses a different method</span></a>
<a class="sourceLine" id="cb53-4" title="4"><span class="co"># than the book, so the results here are slightly different.</span></a></code></pre></div>
</div>
</div>
<div id="section-drilling" class="section level2">
<h2><span class="header-section-number">2.2</span> Drilling</h2>
<div id="section-read-in-data" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Read in data</h3>
<p>Read in the <code>drilling.txt</code> file:</p>
<div class="sourceCode" id="section-cb54"><pre class="sourceCode bash"><code class="sourceCode bash"><a class="sourceLine" id="cb54-1" title="1"><span class="fu">head</span> data/MIPSdata/drilling.txt</a></code></pre></div>
<pre><code>## 5    640.67  830
## 10   674.67  800
## 15   708 711.33
## 20   735.67  867.67
## 25   754.33  940.67
## 30   723.33  941.33
## 35   664.33  924.33
## 40   727.67  873
## 45   658.67  874.67
## 50   658 843.33</code></pre>
<div class="sourceCode" id="section-cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1"><span class="co"># Use the read_tsv (not csv), because this file is &quot;tab-delimited&quot;; the spaces</span></a>
<a class="sourceLine" id="cb56-2" title="2"><span class="co"># between columns contain tab characters.</span></a>
<a class="sourceLine" id="cb56-3" title="3">drilling &lt;-<span class="st"> </span>readr<span class="op">::</span><span class="kw">read_tsv</span>(</a>
<a class="sourceLine" id="cb56-4" title="4">  <span class="dt">file =</span> <span class="st">&quot;data/MIPSdata/drilling.txt&quot;</span>,</a>
<a class="sourceLine" id="cb56-5" title="5">  <span class="dt">col_names =</span> <span class="kw">c</span>(<span class="st">&quot;depth&quot;</span>,<span class="st">&quot;dry&quot;</span>,<span class="st">&quot;wet&quot;</span>),</a>
<a class="sourceLine" id="cb56-6" title="6">  <span class="dt">col_types =</span> <span class="st">&quot;nnn&quot;</span></a>
<a class="sourceLine" id="cb56-7" title="7">)</a>
<a class="sourceLine" id="cb56-8" title="8"><span class="kw">glimpse</span>(drilling)</a></code></pre></div>
<pre><code>## Observations: 80
## Variables: 3
## $ depth [3m[38;5;246m&lt;dbl&gt;[39m[23m 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75,…
## $ dry   [3m[38;5;246m&lt;dbl&gt;[39m[23m 640.67, 674.67, 708.00, 735.67, 754.33, 723.33, 664.33, 72…
## $ wet   [3m[38;5;246m&lt;dbl&gt;[39m[23m 830.00, 800.00, 711.33, 867.67, 940.67, 941.33, 924.33, 87…</code></pre>
</div>
<div id="section-graphical-summaries-1" class="section level3">
<h3><span class="header-section-number">2.2.2</span> Graphical summaries</h3>
<p>To make a scatterplot, you can again use base <code>R</code> or <code>ggplot</code>. We want separate plots
for dry and wet holes. You can do this by plotting these data separately, or you
can re-format the data and have <code>ggplot</code> do it automatically:</p>
<div class="sourceCode" id="section-cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1"><span class="co"># Base R</span></a>
<a class="sourceLine" id="cb58-2" title="2"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) <span class="co"># Plots on a 1 x 2 grid</span></a>
<a class="sourceLine" id="cb58-3" title="3"><span class="kw">plot</span>(dry<span class="op">~</span>depth,<span class="dt">data =</span> drilling)</a>
<a class="sourceLine" id="cb58-4" title="4"><span class="kw">plot</span>(wet<span class="op">~</span>depth,<span class="dt">data =</span> drilling)</a></code></pre></div>
<p><img src="book_files/figure-html/plot-drilling-1-1.png" width="672" /></p>
<div class="sourceCode" id="section-cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1"><span class="co"># ggplot</span></a>
<a class="sourceLine" id="cb59-2" title="2"><span class="co"># Two separate plots:</span></a>
<a class="sourceLine" id="cb59-3" title="3">dryplt &lt;-<span class="st"> </span>drilling <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb59-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> depth,<span class="dt">y =</span> dry)) <span class="op">+</span></a>
<a class="sourceLine" id="cb59-5" title="5"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb59-6" title="6"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">pch =</span> <span class="dv">21</span>) <span class="op">+</span><span class="st"> </span><span class="co"># pch=21 is the magic command to give you hollow points</span></a>
<a class="sourceLine" id="cb59-7" title="7"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Dry Holes&quot;</span>,</a>
<a class="sourceLine" id="cb59-8" title="8">       <span class="dt">x =</span> <span class="st">&quot;Depth&quot;</span>,</a>
<a class="sourceLine" id="cb59-9" title="9">       <span class="dt">y =</span> <span class="st">&quot;Mean drill time&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb59-10" title="10"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">500</span>,<span class="dv">1300</span>,<span class="dt">by =</span> <span class="dv">200</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb59-11" title="11"><span class="st">  </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">500</span>,<span class="dv">1300</span>))</a>
<a class="sourceLine" id="cb59-12" title="12">wetplt &lt;-<span class="st"> </span>drilling <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb59-13" title="13"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> depth,<span class="dt">y =</span> wet)) <span class="op">+</span></a>
<a class="sourceLine" id="cb59-14" title="14"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb59-15" title="15"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">pch =</span> <span class="dv">21</span>) <span class="op">+</span><span class="st"> </span><span class="co"># pch=21 is the magic command to give you hollow points</span></a>
<a class="sourceLine" id="cb59-16" title="16"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Wet Holes&quot;</span>,</a>
<a class="sourceLine" id="cb59-17" title="17">       <span class="dt">x =</span> <span class="st">&quot;Depth&quot;</span>,</a>
<a class="sourceLine" id="cb59-18" title="18">       <span class="dt">y =</span> <span class="st">&quot;Mean drill time&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb59-19" title="19"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">500</span>,<span class="dv">1300</span>,<span class="dt">by =</span> <span class="dv">200</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb59-20" title="20"><span class="st">  </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">500</span>,<span class="dv">1300</span>))</a>
<a class="sourceLine" id="cb59-21" title="21"></a>
<a class="sourceLine" id="cb59-22" title="22">cowplot<span class="op">::</span><span class="kw">plot_grid</span>(dryplt,wetplt,<span class="dt">nrow =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="book_files/figure-html/plot-drilling-1-2.png" width="672" /></p>
<div class="sourceCode" id="section-cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1"><span class="co"># There is a lot of repeated code here. For a better way to make these two</span></a>
<a class="sourceLine" id="cb60-2" title="2"><span class="co"># plots, first create a base plot object and then reuse it:</span></a>
<a class="sourceLine" id="cb60-3" title="3">drillingplt &lt;-<span class="st"> </span>drilling <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb60-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> depth)) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-5" title="5"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb60-6" title="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Depth&quot;</span>,</a>
<a class="sourceLine" id="cb60-7" title="7">       <span class="dt">y =</span> <span class="st">&quot;Mean drill time&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-8" title="8"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">500</span>,<span class="dv">1300</span>,<span class="dt">by =</span> <span class="dv">200</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-9" title="9"><span class="st">  </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">500</span>,<span class="dv">1300</span>))</a>
<a class="sourceLine" id="cb60-10" title="10"></a>
<a class="sourceLine" id="cb60-11" title="11">dryplt2 &lt;-<span class="st"> </span>drillingplt <span class="op">+</span></a>
<a class="sourceLine" id="cb60-12" title="12"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Dry holes&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-13" title="13"><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> dry),<span class="dt">pch =</span> <span class="dv">21</span>)</a>
<a class="sourceLine" id="cb60-14" title="14"></a>
<a class="sourceLine" id="cb60-15" title="15">wetplt2 &lt;-<span class="st"> </span>drillingplt <span class="op">+</span></a>
<a class="sourceLine" id="cb60-16" title="16"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Wet holes&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-17" title="17"><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> wet),<span class="dt">pch =</span> <span class="dv">21</span>)</a>
<a class="sourceLine" id="cb60-18" title="18"></a>
<a class="sourceLine" id="cb60-19" title="19">cowplot<span class="op">::</span><span class="kw">plot_grid</span>(dryplt2,wetplt2,<span class="dt">nrow =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="book_files/figure-html/plot-drilling-1-3.png" width="672" /></p>
<div class="sourceCode" id="section-cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1"><span class="co"># Much better</span></a>
<a class="sourceLine" id="cb61-2" title="2"><span class="co"># Another option is to reformat the data and create the plot</span></a>
<a class="sourceLine" id="cb61-3" title="3"><span class="co"># with a single command. To do this we stack the dry and wet measurements</span></a>
<a class="sourceLine" id="cb61-4" title="4"><span class="co"># on top of each other, and create a new variable which indicates whether the</span></a>
<a class="sourceLine" id="cb61-5" title="5"><span class="co"># measurements are dry or wet. This is called putting the data into &quot;long&quot; format.</span></a>
<a class="sourceLine" id="cb61-6" title="6"><span class="co"># ggplot then knows how to &quot;facet&quot; the plots according to this new variable.</span></a>
<a class="sourceLine" id="cb61-7" title="7"><span class="co"># Check it out:</span></a>
<a class="sourceLine" id="cb61-8" title="8">drilling_long &lt;-<span class="st"> </span>drilling <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb61-9" title="9"><span class="st">  </span>tidyr<span class="op">::</span><span class="kw">gather</span>(type,time,dry<span class="op">:</span>wet) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb61-10" title="10"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">mutate</span>(<span class="dt">type =</span> <span class="kw">case_when</span>( <span class="co"># Rename the type values for plotting</span></a>
<a class="sourceLine" id="cb61-11" title="11">    type <span class="op">==</span><span class="st"> &quot;dry&quot;</span> <span class="op">~</span><span class="st"> &quot;Dry Holes&quot;</span>,</a>
<a class="sourceLine" id="cb61-12" title="12">    type <span class="op">==</span><span class="st"> &quot;wet&quot;</span> <span class="op">~</span><span class="st"> &quot;Wet Holes&quot;</span></a>
<a class="sourceLine" id="cb61-13" title="13">  )) </a>
<a class="sourceLine" id="cb61-14" title="14">dplyr<span class="op">::</span><span class="kw">glimpse</span>(drilling_long)</a></code></pre></div>
<pre><code>## Observations: 160
## Variables: 3
## $ depth [3m[38;5;246m&lt;dbl&gt;[39m[23m 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75,…
## $ type  [3m[38;5;246m&lt;chr&gt;[39m[23m &quot;Dry Holes&quot;, &quot;Dry Holes&quot;, &quot;Dry Holes&quot;, &quot;Dry Holes&quot;, &quot;Dry H…
## $ time  [3m[38;5;246m&lt;dbl&gt;[39m[23m 640.67, 674.67, 708.00, 735.67, 754.33, 723.33, 664.33, 72…</code></pre>
<div class="sourceCode" id="section-cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" title="1">drilling_long <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb63-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> depth,<span class="dt">y =</span> time)) <span class="op">+</span></a>
<a class="sourceLine" id="cb63-3" title="3"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb63-4" title="4"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>type) <span class="op">+</span></a>
<a class="sourceLine" id="cb63-5" title="5"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb63-6" title="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Mean drilling times&quot;</span>,</a>
<a class="sourceLine" id="cb63-7" title="7">       <span class="dt">x =</span> <span class="st">&quot;Depth&quot;</span>,</a>
<a class="sourceLine" id="cb63-8" title="8">       <span class="dt">y =</span> <span class="st">&quot;Mean drilling time&quot;</span>)</a></code></pre></div>
<p><img src="book_files/figure-html/plot-drilling-1-4.png" width="672" /></p>
<div class="sourceCode" id="section-cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1"><span class="co"># Even though there is more overhead with this method, I recommend it because</span></a>
<a class="sourceLine" id="cb64-2" title="2"><span class="co"># it scales to more variables. If you wanted to make 20 plots, you&#39;d have to </span></a>
<a class="sourceLine" id="cb64-3" title="3"><span class="co"># have 20 plots in the previous method but here, the code is actually identical.</span></a></code></pre></div>
<p>To make boxplots, transform the data in the same way as for the side-by-side
scatterplots, and give to <code>ggplot</code>:</p>
<div class="sourceCode" id="section-cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" title="1">drilling_long <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb65-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> type,<span class="dt">y =</span> time)) <span class="op">+</span></a>
<a class="sourceLine" id="cb65-3" title="3"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb65-4" title="4"><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb65-5" title="5"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Boxplots for wet and dry drilling times, Drilling data&quot;</span>,</a>
<a class="sourceLine" id="cb65-6" title="6">       <span class="dt">x =</span> <span class="st">&quot;Hole Type&quot;</span>,</a>
<a class="sourceLine" id="cb65-7" title="7">       <span class="dt">y =</span> <span class="st">&quot;Mean drilling time&quot;</span>)</a></code></pre></div>
<p><img src="book_files/figure-html/plot-drilling-2-1.png" width="672" /></p>
</div>
<div id="section-numerical-summaries" class="section level3">
<h3><span class="header-section-number">2.2.3</span> Numerical summaries</h3>
<p>We can compute numerical summaries of drilling times in the same way as for the
eruption times from the Old Faithful data. However, the drilling data are naturally grouped,
so we should compute our summaries by group— i.e. by hole type, wet or dry.</p>
<p>To do this requires a bit more machinery; we will operate on a dataframe and use
formal grouping operations. This isn’t that much harder, but it’s really powerful.
Check it out:</p>
<div class="sourceCode" id="section-cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" title="1">drilling_long <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb66-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(type) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Everything that happens now happens separately for Wet Holes and Dry Holes</span></a>
<a class="sourceLine" id="cb66-3" title="3"><span class="st">  </span><span class="kw">summarize</span>(</a>
<a class="sourceLine" id="cb66-4" title="4">    <span class="dt">mean =</span> <span class="kw">mean</span>(time),</a>
<a class="sourceLine" id="cb66-5" title="5">    <span class="dt">sd =</span> <span class="kw">sd</span>(time),</a>
<a class="sourceLine" id="cb66-6" title="6">    <span class="dt">min =</span> <span class="kw">min</span>(time),</a>
<a class="sourceLine" id="cb66-7" title="7">    <span class="dt">median =</span> <span class="kw">median</span>(time),</a>
<a class="sourceLine" id="cb66-8" title="8">    <span class="dt">quant_25 =</span> <span class="kw">quantile</span>(time,<span class="dt">probs =</span> <span class="fl">.25</span>),</a>
<a class="sourceLine" id="cb66-9" title="9">    <span class="dt">quant_75 =</span> <span class="kw">quantile</span>(time,<span class="dt">probs =</span> <span class="fl">.75</span>),</a>
<a class="sourceLine" id="cb66-10" title="10">    <span class="dt">max =</span> <span class="kw">max</span>(time)</a>
<a class="sourceLine" id="cb66-11" title="11">  )</a></code></pre></div>
<pre><code>## # A tibble: 2 x 8
##   type       mean    sd   min median quant_25 quant_75   max
##   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
## 1 Dry Holes  806.  154.  584    758.     688.     912. 1238 
## 2 Wet Holes  944.  124.  697.   918.     851.    1030. 1238.</code></pre>
<p>Grouped operations are fundamental to modern data analysis.</p>
</div>
</div>
<div id="section-exercises" class="section level2">
<h2><span class="header-section-number">2.3</span> Exercises</h2>
<ol style="list-style-type: decimal">
<li>The <strong>Janka Hardness</strong> data is in the file <code>jankahardness.txt</code>. Reproduce
the analysis in the book yourself.</li>
</ol>
</div>
<div id="section-extended-example-smoking-and-age-and-mortality" class="section level2">
<h2><span class="header-section-number">2.4</span> Extended example: smoking and age and mortality</h2>
<p>You now have some tools. How do you put them to use in practice? Analyzing data
“in the wild” involves a lot of decision making, and this can impact the conclusions
you make.</p>
<p>Consider a famous dataset containing information on smoking and mortality.
The data is available in the <code>R</code> package <code>faraway</code>. We may load the package and data
and retrieve information on it as follows:</p>
<div class="sourceCode" id="section-cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1"><span class="co"># install.packages(&quot;faraway&quot;) # Run this to install the faraway package, which has useful datasets</span></a>
<a class="sourceLine" id="cb68-2" title="2"><span class="kw">library</span>(faraway) <span class="co"># Attach the faraway package</span></a>
<a class="sourceLine" id="cb68-3" title="3"><span class="kw">data</span>(<span class="st">&quot;femsmoke&quot;</span>) <span class="co"># Load the &quot;femsmoke&quot; data</span></a>
<a class="sourceLine" id="cb68-4" title="4"><span class="co"># ?femsmoke # Run this to open the help page for the dataset.</span></a></code></pre></div>
<p>We see from the help page, and associated reference to the paper in the <em>American Statistician</em>,
that the data comes from asking women in Whickham, England, whether they smoke or not,
and then following up in 20 years to see if they died.</p>
<p>Let’s perform a descriptive analysis of these data. We need some more <em>quantitative</em> pieces of descriptive information. What might we want to know about our data? Some ideas:</p>
<ul>
<li>How many <strong>observations</strong> are there in the data, and what does an observation represent in the context of how the data was collected?</li>
<li>How many <strong>variables</strong> are present in the data, and what does each variable represent in the context of how the data was collected?</li>
<li>How might we summarize each variable? We might compute a <strong>mean</strong> and a <strong>five-number summary</strong> for “continuous” variables, and a <strong>table of counts</strong> for “categorical” variables (more on this later…).</li>
</ul>
<p>Let’s see how we can obtain these descriptive measures in <code>R</code>:</p>
<div class="sourceCode" id="section-cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" title="1"><span class="co"># Get the number of observations (rows), variables, and an idea</span></a>
<a class="sourceLine" id="cb69-2" title="2"><span class="co"># of what the data looks like:</span></a>
<a class="sourceLine" id="cb69-3" title="3"><span class="kw">glimpse</span>(femsmoke)</a></code></pre></div>
<pre><code>## Observations: 28
## Variables: 4
## $ y      &lt;dbl&gt; 2, 1, 3, 5, 14, 7, 27, 12, 51, 40, 29, 101, 13, 64, 53, 6…
## $ smoker &lt;fct&gt; yes, no, yes, no, yes, no, yes, no, yes, no, yes, no, yes…
## $ dead   &lt;fct&gt; yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, ye…
## $ age    &lt;fct&gt; 18-24, 18-24, 25-34, 25-34, 35-44, 35-44, 45-54, 45-54, 5…</code></pre>
<div class="sourceCode" id="section-cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" title="1"><span class="co"># One observation represents a count of people in each category.</span></a>
<a class="sourceLine" id="cb71-2" title="2"><span class="co"># How many people?</span></a>
<a class="sourceLine" id="cb71-3" title="3">femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb71-4" title="4"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_people =</span> <span class="kw">sum</span>(y)) <span class="co"># The summarize() function lets you compute summaries of variables in your dataframe</span></a></code></pre></div>
<pre><code>##   num_people
## 1       1314</code></pre>
<div class="sourceCode" id="section-cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" title="1"><span class="co"># How many smokers?</span></a>
<a class="sourceLine" id="cb73-2" title="2">femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb73-3" title="3"><span class="st">  </span><span class="kw">filter</span>(smoker <span class="op">==</span><span class="st"> &quot;yes&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># filter() lets you choose which rows to keep</span></a>
<a class="sourceLine" id="cb73-4" title="4"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_smokers =</span> <span class="kw">sum</span>(y))</a></code></pre></div>
<pre><code>##   num_smokers
## 1         582</code></pre>
<div class="sourceCode" id="section-cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1"><span class="co"># How many non-smokers?</span></a>
<a class="sourceLine" id="cb75-2" title="2">femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb75-3" title="3"><span class="st">  </span><span class="kw">filter</span>(smoker <span class="op">==</span><span class="st"> &quot;no&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb75-4" title="4"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_non_smokers =</span> <span class="kw">sum</span>(y))</a></code></pre></div>
<pre><code>##   num_non_smokers
## 1             732</code></pre>
<div class="sourceCode" id="section-cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" title="1"><span class="co"># We can get both those numbers at the same time:</span></a>
<a class="sourceLine" id="cb77-2" title="2">femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb77-3" title="3"><span class="st">  </span><span class="kw">group_by</span>(smoker) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># group_by() makes summarize() compute summaries within levels of a variable</span></a>
<a class="sourceLine" id="cb77-4" title="4"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_people =</span> <span class="kw">sum</span>(y))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   smoker num_people
##   &lt;fct&gt;       &lt;dbl&gt;
## 1 yes           582
## 2 no            732</code></pre>
<p>There are lots of other descriptive statistics you could calculate.</p>
<p><em>Summary</em>: descriptive analysis involves communicating properties of a dataset, and the context behind the dataset.</p>
<div id="section-exercises-1" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>How many non-smoking 18-24 year olds are there in the <code>femsmoke</code> data? Answer using <code>filter()</code>.</p></li>
<li><p>How many smokers died? Answer using <code>filter()</code>.</p></li>
<li><p>How many 45-55 year olds did not die?</p></li>
<li><p>Compute the following table using <code>group_by()</code> and <code>summarize()</code>:</p></li>
</ol>
<pre><code>## # A tibble: 7 x 2
##   age   num_people
##   &lt;fct&gt;      &lt;dbl&gt;
## 1 18-24        117
## 2 25-34        281
## 3 35-44        230
## 4 45-54        208
## 5 55-64        236
## 6 65-74        165
## 7 75+           77</code></pre>
<p>Let’s go into a bit more detail. I want to see if there is any apparent association
between smoking and mortality.</p>
<div class="sourceCode" id="section-cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" title="1"><span class="co"># Compute the mortality rate for smokers and non-smokers.</span></a>
<a class="sourceLine" id="cb80-2" title="2"><span class="co"># To do this, create a dataframe containing the numbers of smokers</span></a>
<a class="sourceLine" id="cb80-3" title="3"><span class="co"># and non-smokers</span></a>
<a class="sourceLine" id="cb80-4" title="4">smoker_numbers &lt;-<span class="st"> </span>femsmoke <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># The %&gt;% operator lets you form sequences of operations</span></a>
<a class="sourceLine" id="cb80-5" title="5"><span class="st">  </span><span class="kw">group_by</span>(smoker) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># group_by() makes all the following operations happen within groups</span></a>
<a class="sourceLine" id="cb80-6" title="6"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_people =</span> <span class="kw">sum</span>(y)) <span class="co"># Count the number of people who are smokers and not smokers </span></a>
<a class="sourceLine" id="cb80-7" title="7">smoker_numbers</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   smoker num_people
##   &lt;fct&gt;       &lt;dbl&gt;
## 1 yes           582
## 2 no            732</code></pre>
<div class="sourceCode" id="section-cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" title="1"><span class="co"># Now, compute the number of people who died out of the smokers and non-smokers</span></a>
<a class="sourceLine" id="cb82-2" title="2"><span class="co"># This looks the same as above, except we now filter() only the people who died.</span></a>
<a class="sourceLine" id="cb82-3" title="3">smoker_numbers_dead &lt;-<span class="st"> </span>femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb82-4" title="4"><span class="st">  </span><span class="kw">filter</span>(dead <span class="op">==</span><span class="st"> &quot;yes&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Retains rows where dead == &quot;yes&quot; only</span></a>
<a class="sourceLine" id="cb82-5" title="5"><span class="st">  </span><span class="kw">group_by</span>(smoker) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb82-6" title="6"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_dead =</span> <span class="kw">sum</span>(y))</a>
<a class="sourceLine" id="cb82-7" title="7">smoker_numbers_dead</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   smoker num_dead
##   &lt;fct&gt;     &lt;dbl&gt;
## 1 yes         139
## 2 no          230</code></pre>
<div class="sourceCode" id="section-cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" title="1"><span class="co"># Now, we join these two tables together and compute the mortality rates by group.</span></a>
<a class="sourceLine" id="cb84-2" title="2">smoker_numbers <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb84-3" title="3"><span class="st">  </span><span class="kw">inner_join</span>(smoker_numbers_dead,<span class="dt">by =</span> <span class="st">&quot;smoker&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Joins rows with the same value of &quot;smoker&quot;</span></a>
<a class="sourceLine" id="cb84-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mort_rate =</span> num_dead<span class="op">/</span>num_people) <span class="co"># mutate() creates a new variable, which can be a function of the other variables in the dataframe.</span></a></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   smoker num_people num_dead mort_rate
##   &lt;fct&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 yes           582      139     0.239
## 2 no            732      230     0.314</code></pre>
<p>See anything interesting?</p>
<p>What went wrong? Why are we observing that smokers have a <em>lower</em> mortality rate than
non-smokers? This contradicts the <em>context</em> surrounding this analysis, which in this case is the large body of formal and anecdotal evidence suggesting that smoking is harmful to health.</p>
<p>Did we make a mistake?</p>
<p>One thing we definitely did was ignore some present information. Specifically,
we also know how old the women were. How can we include this information in our
exploratory analysis? We can compute mortality rates by age:</p>
<div class="sourceCode" id="section-cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" title="1">smoker_numbers_age &lt;-<span class="st"> </span>femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb86-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(smoker,age) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Now we&#39;re grouping by smoker AND age. The rest of the code remains unchanged.</span></a>
<a class="sourceLine" id="cb86-3" title="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_people =</span> <span class="kw">sum</span>(y))</a>
<a class="sourceLine" id="cb86-4" title="4"></a>
<a class="sourceLine" id="cb86-5" title="5">smoker_numbers_age_dead &lt;-<span class="st"> </span>femsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb86-6" title="6"><span class="st">  </span><span class="kw">filter</span>(dead <span class="op">==</span><span class="st"> &quot;yes&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb86-7" title="7"><span class="st">  </span><span class="kw">group_by</span>(smoker,age) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb86-8" title="8"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_dead =</span> <span class="kw">sum</span>(y))</a>
<a class="sourceLine" id="cb86-9" title="9"></a>
<a class="sourceLine" id="cb86-10" title="10">smoker_numbers_age <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb86-11" title="11"><span class="st">  </span><span class="kw">inner_join</span>(smoker_numbers_age_dead,<span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;smoker&quot;</span>,<span class="st">&quot;age&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb86-12" title="12"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mort_rate =</span> num_dead<span class="op">/</span>num_people)</a></code></pre></div>
<pre><code>## # A tibble: 14 x 5
## # Groups:   smoker [2]
##    smoker age   num_people num_dead mort_rate
##    &lt;fct&gt;  &lt;fct&gt;      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
##  1 yes    18-24         55        2    0.0364
##  2 yes    25-34        124        3    0.0242
##  3 yes    35-44        109       14    0.128 
##  4 yes    45-54        130       27    0.208 
##  5 yes    55-64        115       51    0.443 
##  6 yes    65-74         36       29    0.806 
##  7 yes    75+           13       13    1     
##  8 no     18-24         62        1    0.0161
##  9 no     25-34        157        5    0.0318
## 10 no     35-44        121        7    0.0579
## 11 no     45-54         78       12    0.154 
## 12 no     55-64        121       40    0.331 
## 13 no     65-74        129      101    0.783 
## 14 no     75+           64       64    1</code></pre>
<p>Older people are more likely to die within the 20 year followup period.
However, examining the raw counts of people in each group, we also see that
<em>in these data, older people are less likely to smoke</em> than younger people. So
<em>in these data</em>, less smokers died, because less smokers were old, and more
old people died.</p>
<p>Before moving on, get some practice doing exploratory analysis with the following
exercises:</p>
</div>
<div id="section-exercises-2" class="section level3">
<h3><span class="header-section-number">2.4.2</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li>What is the <em>relative risk</em> of mortality—the ratio of the mortality rates—for
smoking 18-24 year olds vs non-smoking 18-24 year olds? Compute the answer manually by
reading the numbers off the above table. Then compute it using <code>R</code> by doing the
following:</li>
</ol>
<ul>
<li>Create two datasets using <code>filter()</code>: one containing smokers and one containing
non-smokers. <code>filter()</code> out only the 18-24 year olds. This gives you two datasets
each with only one row. For example, <code>smokers &lt;- femsmoke %&gt;% filter(smoker == &quot;yes&quot;,age = &quot;18-24&quot;)</code>.</li>
<li><code>inner_join()</code> the two datasets together, using <code>age</code> as the <code>by</code> variable:
<code>smokers %&gt;% inner_join(???,by = &quot;age&quot;)</code></li>
</ul>
<ol style="list-style-type: decimal">
<li><em>Advanced</em>: modify the above steps to create the following table of relative mortality rates. You should start from a cleaned up version of the mortality rate by age table:</li>
</ol>
<div class="sourceCode" id="section-cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" title="1">rates_by_age &lt;-<span class="st"> </span>smoker_numbers_age <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb88-2" title="2"><span class="kw">inner_join</span>(smoker_numbers_age_dead,<span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;smoker&quot;</span>,<span class="st">&quot;age&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb88-3" title="3"><span class="kw">mutate</span>(<span class="dt">mort_rate =</span> num_dead<span class="op">/</span>num_people) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb88-4" title="4"><span class="kw">ungroup</span>() <span class="co"># The data was previously grouped, we don&#39;t want this anymore</span></a></code></pre></div>
<p>Use <code>dplyr::select()</code> to remove and rename columns, see <code>?dplyr::select</code>. You
should get the following:</p>
<pre><code>## # A tibble: 7 x 4
##   age   smoker_mort_rate nonsmoker_mort_rate relative_risk
##   &lt;fct&gt;            &lt;dbl&gt;               &lt;dbl&gt;         &lt;dbl&gt;
## 1 18-24           0.0364              0.0161         2.25 
## 2 25-34           0.0242              0.0318         0.760
## 3 35-44           0.128               0.0579         2.22 
## 4 45-54           0.208               0.154          1.35 
## 5 55-64           0.443               0.331          1.34 
## 6 65-74           0.806               0.783          1.03 
## 7 75+             1                   1              1</code></pre>
</div>
</div>
<div id="section-case-study-rental-housing-in-toronto" class="section level2">
<h2><span class="header-section-number">2.5</span> Case study: rental housing in Toronto</h2>
<p>The RentSafeTO: Apartment Building Standards program is designed to help renters
in the city of Toronto make informed choices about where to live, and to enforce
a minimum standard of quality upon rental units within the city. With rents
skyrocketing and home ownership not a reasonable option for most, having an
informed view of the rental market is imperative for Toronto residents. It also helps keep leaders
accountable, specifically if we focus on social and community housing buildings.</p>
<p>Comprehensive and fairly clean data from the program, along with specific
information, is available at <a href="https://open.toronto.ca/dataset/apartment-building-evaluation/" class="uri">https://open.toronto.ca/dataset/apartment-building-evaluation/</a>.
Data for the following were downloaded on <code>2019/09/16</code>.</p>
<p>To start your analysis, go now and download the data
and open it in a spreadsheet and have a look. Familiarize yourselves with the
variable descriptions and how the data were collected; the <em>documentation</em>. This somewhat tedious
task is a first step of <strong>any</strong> data analysis, in academia, industry, government,
or wherever.</p>
<div id="section-load-the-data" class="section level3">
<h3><span class="header-section-number">2.5.1</span> Load the data</h3>
<p>The data are stored in a <code>.csv</code> file, which stands for “comma-separated-values”.
Storing data in a text file with a separator, usually a comma, is very common.
These are referred to as “flat files” in an industrial context, to distinguish
them from data stored in databases.</p>
<p>We may read the data into <code>R</code> using the <code>read_csv</code> function in the <code>readr</code> package.
The <code>readr</code> package is part of the <code>tidyverse</code> package that we used before, so if
you installed that package, you have it loaded.</p>
<div class="sourceCode" id="section-cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" title="1"><span class="co"># https://open.toronto.ca/dataset/apartment-building-evaluation/</span></a>
<a class="sourceLine" id="cb90-2" title="2"><span class="co"># install.packages(&quot;readr&quot;)</span></a>
<a class="sourceLine" id="cb90-3" title="3"></a>
<a class="sourceLine" id="cb90-4" title="4"><span class="co"># Read the data in. This means call the readr::read_csv() function, point it</span></a>
<a class="sourceLine" id="cb90-5" title="5"><span class="co"># to where you saved the data on your computer, and then save the result to a</span></a>
<a class="sourceLine" id="cb90-6" title="6"><span class="co"># variable. I am naming this variable &#39;apartmentdata&#39;.</span></a>
<a class="sourceLine" id="cb90-7" title="7"><span class="co"># Type ?readr::read_csv if you want to read about this function.</span></a>
<a class="sourceLine" id="cb90-8" title="8">apartmentdata &lt;-<span class="st"> </span>readr<span class="op">::</span><span class="kw">read_csv</span>(</a>
<a class="sourceLine" id="cb90-9" title="9">  <span class="dt">file =</span> <span class="st">&quot;data/apartment-data/toronto-apartment-building-evaluations.csv&quot;</span></a>
<a class="sourceLine" id="cb90-10" title="10">)</a></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   EVALUATION_COMPLETED_ON = col_character(),
##   PROPERTY_TYPE = col_character(),
##   RESULTS_OF_SCORE = col_character(),
##   SITE_ADDRESS = col_character(),
##   WARD = col_character()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<p>The message displayed is telling you that <code>readr::read_csv()</code> guessed at what
kind of data were in each column, i.e. numbers, letters, dates, etc. You should
make sure, as I have while writing, that these are what you expect. You can
get a concise view of this dataset using the <code>glimpse</code> function in the <code>dplyr</code>
package, which is automatically loaded when you load the <code>tidyverse</code>:</p>
<div class="sourceCode" id="section-cb93"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb93-1" title="1"><span class="kw">glimpse</span>(apartmentdata)</a></code></pre></div>
<pre><code>## Observations: 3,446
## Variables: 32
## $ `_id`                       &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1…
## $ BALCONY_GUARDS              &lt;dbl&gt; NA, NA, NA, NA, 5, NA, 5, 3, 4, 4, 3…
## $ CONFIRMED_STOREYS           &lt;dbl&gt; 28, 4, 3, 3, 29, 3, 7, 18, 17, 32, 4…
## $ CONFIRMED_UNITS             &lt;dbl&gt; 457, 15, 26, 10, 272, 12, 95, 287, 3…
## $ ELEVATORS                   &lt;dbl&gt; 4, NA, NA, NA, 5, NA, 5, 4, 5, 4, NA…
## $ ENTRANCE_DOORS_WINDOWS      &lt;dbl&gt; 3, 3, 3, 4, 5, 4, 4, 4, 3, 4, 4, 3, …
## $ ENTRANCE_LOBBY              &lt;dbl&gt; 4, 3, 3, 4, 5, 4, 4, 4, 4, 4, 4, 4, …
## $ EVALUATION_COMPLETED_ON     &lt;chr&gt; &quot;04/03/2019&quot;, &quot;05/24/2018&quot;, &quot;07/11/2…
## $ EXTERIOR_CLADDING           &lt;dbl&gt; 3, 4, 4, 4, 5, 4, 5, 4, 4, 3, 3, 4, …
## $ EXTERIOR_GROUNDS            &lt;dbl&gt; 3, 4, 3, 3, 5, 4, 5, 4, 3, 4, 3, 4, …
## $ EXTERIOR_WALKWAYS           &lt;dbl&gt; 3, 5, 4, 4, 5, 4, 5, 4, 3, 4, 4, 3, …
## $ GARBAGE_BIN_STORAGE_AREA    &lt;dbl&gt; 3, 4, 3, 3, 4, 3, 3, 3, 4, 4, 4, 4, …
## $ GARBAGE_CHUTE_ROOMS         &lt;dbl&gt; 3, NA, NA, NA, 5, NA, 5, 4, 3, 4, 5,…
## $ GRAFFITI                    &lt;dbl&gt; 5, 5, 5, 5, 5, 4, 5, 4, 3, 4, 5, 5, …
## $ INTERIOR_LIGHTING_LEVELS    &lt;dbl&gt; 3, 4, 4, 4, 5, 4, 4, 3, 3, 4, 3, 4, …
## $ INTERIOR_WALL_CEILING_FLOOR &lt;dbl&gt; 4, 3, 4, 4, 5, 4, 4, 3, 4, 4, 4, 3, …
## $ INTERNAL_GUARDS_HANDRAILS   &lt;dbl&gt; 3, 4, 3, 4, 5, 4, 5, 4, 4, 4, 5, 4, …
## $ NO_OF_AREAS_EVALUATED       &lt;dbl&gt; 18, 14, 14, 13, 19, 16, 17, 18, 19, …
## $ OTHER_FACILITIES            &lt;dbl&gt; 4, NA, NA, NA, 5, NA, NA, NA, NA, NA…
## $ PARKING_AREA                &lt;dbl&gt; 2, NA, NA, NA, 4, 3, 5, 2, 4, 4, 2, …
## $ PROPERTY_TYPE               &lt;chr&gt; &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;SO…
## $ RESULTS_OF_SCORE            &lt;chr&gt; &quot;Evaluation needs to be conducted in…
## $ RSN                         &lt;dbl&gt; 4365723, 4364249, 4408585, 4288126, …
## $ SCORE                       &lt;dbl&gt; 71, 77, 71, 78, 98, 76, 93, 72, 74, …
## $ SECURITY                    &lt;dbl&gt; 4, 3, 3, 4, 5, 4, 5, 3, 4, 4, 4, 4, …
## $ SITE_ADDRESS                &lt;chr&gt; &quot;2350  DUNDAS ST W&quot;, &quot;9  STAG HILL D…
## $ STAIRWELLS                  &lt;dbl&gt; 4, 4, 3, 4, 5, 4, 5, 4, 4, 4, 3, 4, …
## $ STORAGE_AREAS_LOCKERS       &lt;dbl&gt; NA, NA, NA, NA, NA, 4, NA, NA, 3, 4,…
## $ WARD                        &lt;chr&gt; &quot;04&quot;, &quot;19&quot;, &quot;11&quot;, &quot;04&quot;, &quot;07&quot;, &quot;03&quot;, …
## $ WATER_PEN_EXT_BLDG_ELEMENTS &lt;dbl&gt; 4, 4, 4, 4, 5, 4, 5, 4, 5, 3, 3, 4, …
## $ YEAR_BUILT                  &lt;dbl&gt; 1976, 1953, 1948, 1920, 2017, 1967, …
## $ YEAR_REGISTERED             &lt;dbl&gt; 2018, 2018, 2018, 2017, 2018, 2017, …</code></pre>
<p>That’s bigger than the <code>smoking</code> data! 3,446 rental apartment buildings, each with
32 factors measured. The buliding’s address and Ward number are in there, which are
helpful for characterizing neighbourhoods.</p>
</div>
<div id="section-analysis-i-what-does-the-data-look-like" class="section level3">
<h3><span class="header-section-number">2.5.2</span> Analysis I: what does the data look like?</h3>
<p>As a first step, we want to get an idea of what our data “looks like”. This typically means picking some interesting variables and summarizing their distributions somehow.</p>
<p>Which variables to pick will depend on the context. Often it will be clear which variables are important, and sometimes not.</p>
<p>Because you read the documentation and familiarized yourselves with the variables in the dataset, you know that there is a variable called <code>SCORE</code> which sums up the individual category scores for each building. In the context of determining building quality, this seems like an important variable to look at.</p>
<p>We’ll summarize the distribution of <code>SCORE</code> using a five-number summary and mean, and a <strong>histogram</strong> with a <strong>kernel density estimate</strong>.</p>
<p>First, prepare the data for analysis:</p>
<div class="sourceCode" id="section-cb95"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb95-1" title="1"><span class="co"># First, select only the columns you want</span></a>
<a class="sourceLine" id="cb95-2" title="2"><span class="co"># This isn&#39;t strictly necessary but trust me, it makes </span></a>
<a class="sourceLine" id="cb95-3" title="3"><span class="co"># debugging WAY easier.</span></a>
<a class="sourceLine" id="cb95-4" title="4"><span class="co"># I&#39;m also renaming the columns so the dataframe looks prettier.</span></a>
<a class="sourceLine" id="cb95-5" title="5"><span class="co"># Again, trust me. This stuff matters.</span></a>
<a class="sourceLine" id="cb95-6" title="6">apartmentclean &lt;-<span class="st"> </span>apartmentdata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb95-7" title="7"><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(SCORE)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Remove apartments with missing scores</span></a>
<a class="sourceLine" id="cb95-8" title="8"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="dt">ward =</span> WARD,</a>
<a class="sourceLine" id="cb95-9" title="9">                <span class="dt">score =</span> SCORE,</a>
<a class="sourceLine" id="cb95-10" title="10">                <span class="dt">property_type =</span> PROPERTY_TYPE,</a>
<a class="sourceLine" id="cb95-11" title="11">                <span class="dt">year_built =</span> YEAR_BUILT,</a>
<a class="sourceLine" id="cb95-12" title="12">                <span class="dt">address =</span> SITE_ADDRESS</a>
<a class="sourceLine" id="cb95-13" title="13">  )</a>
<a class="sourceLine" id="cb95-14" title="14"><span class="kw">glimpse</span>(apartmentclean) <span class="co"># Much nicer!</span></a></code></pre></div>
<pre><code>## Observations: 3,437
## Variables: 5
## $ ward          &lt;chr&gt; &quot;04&quot;, &quot;19&quot;, &quot;11&quot;, &quot;04&quot;, &quot;07&quot;, &quot;03&quot;, &quot;17&quot;, &quot;17&quot;, &quot;0…
## $ score         &lt;dbl&gt; 71, 77, 71, 78, 98, 76, 93, 72, 74, 78, 73, 76, 57…
## $ property_type &lt;chr&gt; &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;SOCIAL HOUSING&quot;,…
## $ year_built    &lt;dbl&gt; 1976, 1953, 1948, 1920, 2017, 1967, 2015, 1970, 19…
## $ address       &lt;chr&gt; &quot;2350  DUNDAS ST W&quot;, &quot;9  STAG HILL DR&quot;, &quot;130  MACP…</code></pre>
<p>To compute the five-number summary (plus mean), use the <code>summary()</code> function in <code>R</code>. I also want to know the <em>standard deviation</em> of <code>SCORE</code>:</p>
<div class="sourceCode" id="section-cb97"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb97-1" title="1"><span class="kw">summary</span>(apartmentclean<span class="op">$</span>score)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   37.00   68.00   72.00   72.28   77.00   99.00</code></pre>
<div class="sourceCode" id="section-cb99"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb99-1" title="1"><span class="kw">sd</span>(apartmentclean<span class="op">$</span>score,<span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## [1] 7.117172</code></pre>
<p>The worst building in the city has a total score of 37, and the best gets 99. The median score—half the buildings in the city have a lower score, and half a higher score than this—is 72, and this roughly equals the mean of 72.28. 25% of buildings score higher than 77, and 25% score lower than 68. So most buildings seem to fall within less than one standard deviation of the mean, which indicates that these data are fairly <em>concentrated</em> about their mean.</p>
<p>To provide some context, go look up your own building (if you live in a rental building) or that of a friend in the data. Where does your building fall in terms of quality within Toronto?</p>
<p>So far we have used tabular displays to summarize our data, for both the <code>smoking</code> and the apartment data.
We also learned about graphical displays. Let’s see a histogram of the scores, with a kernel density
estimate:</p>
<p>We can make a histogram in <code>R</code> as follows:</p>
<div class="sourceCode" id="section-cb101"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb101-1" title="1"><span class="co"># The ggplot2 package is loaded as part of the tidyverse</span></a>
<a class="sourceLine" id="cb101-2" title="2">score_histogram &lt;-<span class="st"> </span>apartmentclean <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb101-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> score)) <span class="op">+</span><span class="st"> </span><span class="co"># Tell ggplot to use score on the x axis</span></a>
<a class="sourceLine" id="cb101-4" title="4"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span><span class="st"> </span><span class="co"># Make the plot pretty</span></a>
<a class="sourceLine" id="cb101-5" title="5"><span class="st">  </span><span class="kw">geom_histogram</span>( <span class="co"># Makes a histogram</span></a>
<a class="sourceLine" id="cb101-6" title="6">    <span class="kw">aes</span>(<span class="dt">y =</span> ..density..),</a>
<a class="sourceLine" id="cb101-7" title="7">    <span class="dt">bins =</span> <span class="dv">20</span>,</a>
<a class="sourceLine" id="cb101-8" title="8">    <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>,</a>
<a class="sourceLine" id="cb101-9" title="9">    <span class="dt">fill =</span> <span class="st">&quot;lightgrey&quot;</span></a>
<a class="sourceLine" id="cb101-10" title="10">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb101-11" title="11"><span class="st">  </span><span class="kw">geom_density</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb101-12" title="12"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of RentSafeTO Apartment Building Standards score&quot;</span>,</a>
<a class="sourceLine" id="cb101-13" title="13">       <span class="dt">x =</span> <span class="st">&quot;Score&quot;</span>,</a>
<a class="sourceLine" id="cb101-14" title="14">       <span class="dt">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb101-15" title="15"><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">30</span>,<span class="dv">100</span>,<span class="dt">by =</span> <span class="dv">5</span>))</a>
<a class="sourceLine" id="cb101-16" title="16"></a>
<a class="sourceLine" id="cb101-17" title="17">score_histogram</a></code></pre></div>
<p><img src="book_files/figure-html/apartment-descriptive-3-1.png" width="672" /></p>
<p>It appears that most buildings are in the 65 to 85 range. I actually just moved
from a building that has a 66 to a building that has an 86. The difference
is substantial!</p>
</div>
<div id="section-analysis-ii-do-different-wards-have-different-quality-housing" class="section level3">
<h3><span class="header-section-number">2.5.3</span> Analysis II: Do different wards have different quality housing?</h3>
<p>A Ward is an administrative district within the city that has a single city
counsellor. If I’m thinking about moving to, or within, Toronto, I want to know:
<strong>Do different wards have different quality housing?</strong>.</p>
<p>In order to address this question we need to decide on the following:</p>
<ul>
<li><strong>Variable of interest</strong>. How do we <em>quantify</em> our research question? We need
to pick a <em>measure of quality</em>. Picking different measures can lead to different
conclusions.</li>
<li><strong>Filters</strong>. Do we look at all apartment buildings? Should we look only at those
built after, or before, a certain date? Only those that meet a certain minimum,
or maximum, standard of quality according to our definition? Are there any other
kinds of decisions we might have to consider?</li>
<li><strong>Methods</strong>. What kind of statistical tools should we use to address our research
question? We need to pick descriptive statistics to report, and decide whether
we want to include other auxillary variables in the analysis.</li>
<li><strong>Conclusions</strong>. How do we report our results? Tables, charts, maps? Should we
include subjective, editorial commentary, or let the data speak for
themselves?</li>
</ul>
<p>This is already overwhelming! Let’s make an attempt at it. I propose:</p>
<ul>
<li>Our <strong>variable of interest</strong> should be <code>SCORE</code>, which you know (because you
read the documentation…) is the “overall score of the buliding”. Higher is
better. The actual formula is included in the documentation of the data.</li>
<li>We will <strong>filter</strong> the data to only include buildings where <code>PROPERTY_TYPE == 'PRIVATE'</code>,
which will restrict our analysis to not include social housing. The quality of social
housing is an important social justice issue (that you will investigate in the exercises)
but it’s somewhat separate (?) from the question of where to look for rental housing.</li>
<li>Our <strong>methods</strong> will include looking at a table of average scores for each ward.
We will also look at whether older or newer buildings receive better scores.</li>
<li>We will summarize our <strong>conclusions</strong> through a subjective assessment of the
above table of average scores.</li>
</ul>
<p>With these decisions made, we may proceed with our analysis using the <code>tidyverse</code>
as follows:</p>
<div class="sourceCode" id="section-cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" title="1"><span class="co"># Apply filter(s).</span></a>
<a class="sourceLine" id="cb102-2" title="2">apartmentfiltered &lt;-<span class="st"> </span>apartmentclean <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb102-3" title="3"><span class="st">  </span><span class="kw">filter</span>(property_type <span class="op">==</span><span class="st"> &quot;PRIVATE&quot;</span>)</a>
<a class="sourceLine" id="cb102-4" title="4"><span class="co"># When filtering, always compare the filtered and unfiltered data to ensure</span></a>
<a class="sourceLine" id="cb102-5" title="5"><span class="co"># the result is as expected:</span></a>
<a class="sourceLine" id="cb102-6" title="6"><span class="kw">glimpse</span>(apartmentclean)</a></code></pre></div>
<pre><code>## Observations: 3,437
## Variables: 5
## $ ward          &lt;chr&gt; &quot;04&quot;, &quot;19&quot;, &quot;11&quot;, &quot;04&quot;, &quot;07&quot;, &quot;03&quot;, &quot;17&quot;, &quot;17&quot;, &quot;0…
## $ score         &lt;dbl&gt; 71, 77, 71, 78, 98, 76, 93, 72, 74, 78, 73, 76, 57…
## $ property_type &lt;chr&gt; &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;SOCIAL HOUSING&quot;,…
## $ year_built    &lt;dbl&gt; 1976, 1953, 1948, 1920, 2017, 1967, 2015, 1970, 19…
## $ address       &lt;chr&gt; &quot;2350  DUNDAS ST W&quot;, &quot;9  STAG HILL DR&quot;, &quot;130  MACP…</code></pre>
<div class="sourceCode" id="section-cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" title="1"><span class="kw">glimpse</span>(apartmentfiltered)</a></code></pre></div>
<pre><code>## Observations: 2,873
## Variables: 5
## $ ward          &lt;chr&gt; &quot;04&quot;, &quot;19&quot;, &quot;11&quot;, &quot;07&quot;, &quot;03&quot;, &quot;17&quot;, &quot;17&quot;, &quot;08&quot;, &quot;1…
## $ score         &lt;dbl&gt; 71, 77, 71, 98, 76, 93, 72, 74, 78, 73, 76, 57, 70…
## $ property_type &lt;chr&gt; &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;PRIVATE&quot;, &quot;PRIVA…
## $ year_built    &lt;dbl&gt; 1976, 1953, 1948, 2017, 1967, 2015, 1970, 1976, 19…
## $ address       &lt;chr&gt; &quot;2350  DUNDAS ST W&quot;, &quot;9  STAG HILL DR&quot;, &quot;130  MACP…</code></pre>
<div class="sourceCode" id="section-cb106"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb106-1" title="1"><span class="kw">nrow</span>(apartmentclean) <span class="op">-</span><span class="st"> </span><span class="kw">nrow</span>(apartmentfiltered) <span class="co"># Dropped 567 rows.</span></a></code></pre></div>
<pre><code>## [1] 564</code></pre>
<div class="sourceCode" id="section-cb108"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb108-1" title="1"><span class="co"># Now create the table of averages:</span></a>
<a class="sourceLine" id="cb108-2" title="2">apartmentfiltered <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb108-3" title="3"><span class="st">  </span><span class="kw">group_by</span>(ward) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb108-4" title="4"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">avg_score =</span> <span class="kw">mean</span>(score))</a></code></pre></div>
<pre><code>## # A tibble: 26 x 2
##    ward  avg_score
##    &lt;chr&gt;     &lt;dbl&gt;
##  1 01         71.5
##  2 02         73.0
##  3 03         70.5
##  4 04         68.2
##  5 05         71.7
##  6 06         72.1
##  7 07         69.8
##  8 08         73.5
##  9 09         67.5
## 10 10         72.2
## # … with 16 more rows</code></pre>
<p>Bah! What happened? Why are there these <code>NA</code> values?</p>
<p><code>NA</code> is the value <code>R</code> uses to mean “missing”. We have to hope that whether a
rental apartment building’s <code>score</code> is missing <em>is not related</em> to what that score <em>is</em>,
that is, we hope apartments with higher or lower scores aren’t missing more often.</p>
<p>We will ignore missingness for now. To do this, use the <code>na.rm = TRUE</code> option in
<code>mean</code>:</p>
<div class="sourceCode" id="section-cb110"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb110-1" title="1">apartmentsummary &lt;-<span class="st"> </span>apartmentfiltered <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb110-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(ward) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb110-3" title="3"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">avg_score =</span> <span class="kw">mean</span>(score,<span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</a>
<a class="sourceLine" id="cb110-4" title="4">apartmentsummary</a></code></pre></div>
<pre><code>## # A tibble: 26 x 2
##    ward  avg_score
##    &lt;chr&gt;     &lt;dbl&gt;
##  1 01         71.5
##  2 02         73.0
##  3 03         70.5
##  4 04         68.2
##  5 05         71.7
##  6 06         72.1
##  7 07         69.8
##  8 08         73.5
##  9 09         67.5
## 10 10         72.2
## # … with 16 more rows</code></pre>
<p>This isn’t a super friendly way of comparing these 26 numbers. I’d rather use a
graphical display, like the boxplots we learned about in chapters 15 and 16:</p>
<div class="sourceCode" id="section-cb112"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb112-1" title="1">apartmentfiltered <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb112-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> ward,<span class="dt">y =</span> score)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb112-3" title="3"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb112-4" title="4"><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb112-5" title="5"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;ABS score shows moderate variability across wards in Toronto&quot;</span>,</a>
<a class="sourceLine" id="cb112-6" title="6">       <span class="dt">x =</span> <span class="st">&quot;Ward&quot;</span>,</a>
<a class="sourceLine" id="cb112-7" title="7">       <span class="dt">y =</span> <span class="st">&quot;ABS Score&quot;</span>) </a></code></pre></div>
<p><img src="book_files/figure-html/barchart-apartment-1-1.png" width="672" /></p>
<p>It looks like some wards are better than others. Or are they? Can we make any
definitive conclusions based on this?</p>
</div>
<div id="section-analysis-iii-trends-in-quality-over-time" class="section level3">
<h3><span class="header-section-number">2.5.4</span> Analysis III: trends in quality over time</h3>
<p>Let’s go further and analyze some other interesting aspects of these data. I’m
interested in knowing: <strong>Are newer buildings higher quality</strong>?</p>
<p>We have the <code>score</code>
and the <code>year_built</code>, and we’d like to investigate whether newer buildings (higher
<code>year_built</code>) have higher <code>scores</code>. We have another decision to make. We could
consider <code>year_built</code> to be a categorical variable, and make a bar chart. Or,
we could consider it to be a continuous variable.</p>
<p>Because values of <code>year_built</code> are inherently comparable, and because <em>our research
question involves making such comparisons</em>, we will consider <code>year_built</code> to be
a continuous variable.</p>
<p>One type of plot used to compare continuous variables is a <strong>scatterplot</strong>. A
scatterplot has continuous variables on the x- and y-axes, and draws a point (or
bubble) at each place in the two-dimensional plane where a datapoint occurs. We
can make this kind of plot in <code>ggplot2</code> as well. This time, we use the raw
(well, cleaned and filtered) data:</p>
<div class="sourceCode" id="section-cb113"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb113-1" title="1">apartmentfiltered <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb113-2" title="2"><span class="st">  </span><span class="kw">filter</span>(year_built <span class="op">&gt;</span><span class="st"> </span><span class="dv">1900</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb113-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year_built,<span class="dt">y =</span> score)) <span class="op">+</span></a>
<a class="sourceLine" id="cb113-4" title="4"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb113-5" title="5"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">pch =</span> <span class="dv">21</span>,<span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>,<span class="dt">fill =</span> <span class="st">&quot;grey&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="co"># pch=21 makes the bubbles hollow, looks nice</span></a>
<a class="sourceLine" id="cb113-6" title="6"><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">1900</span>,<span class="dv">2020</span>,<span class="dt">by=</span><span class="dv">10</span>)) <span class="op">+</span><span class="st"> </span><span class="co"># Set the x-axis range</span></a>
<a class="sourceLine" id="cb113-7" title="7"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Less rental buildings are being built recently, but they are of higher quality&quot;</span>,</a>
<a class="sourceLine" id="cb113-8" title="8">       <span class="dt">x =</span> <span class="st">&quot;Year Built&quot;</span>,</a>
<a class="sourceLine" id="cb113-9" title="9">       <span class="dt">y =</span> <span class="st">&quot;ABS Score&quot;</span>)</a></code></pre></div>
<p><img src="book_files/figure-html/apartment-plot-2-1.png" width="672" /></p>
<p>Very interesting. You can clearly see the baby boom of the 1950’s to 1970’s, followed by a massive slowdown in construction during the economic slump in the 1980’s, and a complete stop when rent control was introduced in 1991 (remember, these are <em>rental</em> buildings only). Then, we see a new wave of
rental building construction, and the new buildings seem to be of higher quality.</p>
<p>What are the highest and lowest quality rental buildings in Toronto?</p>
<div class="sourceCode" id="section-cb114"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb114-1" title="1"><span class="co"># Get the 10 highest scoring buildings</span></a>
<a class="sourceLine" id="cb114-2" title="2">apartmentfiltered <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb114-3" title="3"><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(score)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Sort the data, descending, by score</span></a>
<a class="sourceLine" id="cb114-4" title="4"><span class="st">  </span><span class="kw">slice</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>) <span class="co"># Take the first ten- i.e. the top ten</span></a></code></pre></div>
<pre><code>## # A tibble: 10 x 5
##    ward  score property_type year_built address                 
##    &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;                   
##  1 YY       99 PRIVATE             2018 561  SHERBOURNE ST      
##  2 17       99 PRIVATE             2017 123  PARKWAY FOREST DR  
##  3 16       99 PRIVATE             1963 70  PARKWOODS VILLAGE DR
##  4 07       98 PRIVATE             2017 2  VENA WAY             
##  5 17       97 PRIVATE             1968 24  FOREST MANOR RD     
##  6 12       96 PRIVATE             1960 42  GLEN ELM AVE        
##  7 13       95 PRIVATE             2017 252  VICTORIA ST        
##  8 02       95 PRIVATE             1969 500  SCARLETT RD        
##  9 16       95 PRIVATE             1962 67  PARKWOODS VILLAGE DR
## 10 07       95 PRIVATE             2016 6  VENA WAY</code></pre>
<p>Wow. I know where I want to live.</p>
</div>
<div id="section-summary" class="section level3">
<h3><span class="header-section-number">2.5.5</span> Summary</h3>
<p>We have seen how even something simple like trying to figure out whether
different areas of the city have different quality housing can require
a lot of decision making. And these decisions require expertise. By taking
a principled approach to learning <strong>data analysis</strong>, you are <em>empowering</em>
yourself to live a life that is better informed.</p>
<p>But notice that we didn’t really answer any questions in this chapter. We
saw some rough patterns, but were they real? If we made different decisions, or if we <em>sampled different data</em>, would we have seen different patterns?</p>
<p>In order to understand what the problem is and how to approach it, we
need to take a more detailed look at the concept of <strong>error</strong>.</p>
</div>
<div id="section-exercises-3" class="section level3">
<h3><span class="header-section-number">2.5.6</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Take each of the analyses we have performed on the Toronto rental data and say whether you think it’s <strong>descriptive</strong>, <strong>exploratory</strong>, or <strong>prescriptive</strong>, or a mix, and say why.</p></li>
<li><p>What is that “YY” ward that shows up in the dot plot? Investigate this unusual observation.</p></li>
<li><p>Read the documentation online and choose three variables that you find the most interesting. Reproduce the analyses I, II and III using your variables. Is there more or less variability across wards than with <code>score</code>?</p></li>
<li><p>What is the ward with the highest average score? In what ward is/are the building(s) with the highest score(s)? Is this the same ward, or not? Would you expect the ward with the highest average to also have the highest-scoring buildings? Repeat this question with the lowest scoring buildings instead of the highest.</p></li>
<li><p>If you live in a rental apartment, find it in these data. If not, find a friend’s place. How does your building compare to other buildings in your ward? Does it score higher or lower? The <code>filter()</code> function is your friend here, or you can use <code>apartmentfiltered %&gt;% arrange(SITE_ADDRESS) %&gt;% print(n = Inf)</code> and then find yours in the list manually.</p></li>
<li><p>Combine the analyses of sections 2.3.2 and 2.3.3. with that of 2.3.4. Specifically, make a table and a boxplot of the average score by year. This means replace <code>ward</code> by <code>year_built</code> in the analysis of sections 2.3.2. and 2.3.3. Do your conclusions change when comparing with 2.3.4? Why or why not? Would you expect this to always be the case?</p></li>
<li><p><em>Advanced</em>: analyze the quality of <strong>social housing</strong> in Toronto. Perform a similar analysis to what we performed here for <code>PROPERTY_TYPE == 'PRIVATE'</code>, but instead for <code>PROPERTY_TYPE %in% c('SOCIAL HOUSING','TCHC')</code> (equivalent to <code>PROPERTY_TYPE != 'PRIVATE'</code>). Does the quality of social housing in Toronto vary greatly across different wards? Is it improving or degrading over time? Do you think we have enough information here to definitively answer these questions?</p></li>
</ol>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="section-supplement-to-chapters-13-and-14.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["book.pdf", "book.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
